/* ============================================================
   WanderAlt — content catalog (static fallback)
   ------------------------------------------------------------
   Auto-generated snapshot from live DB. Regenerate with:
     node .scripts/regen-catalog.js
   This is loaded first; supabase.js then replaces it with live
   data when the network is reachable.

   The raw multi-city list is exposed as `window.WA._catalogAll`;
   `window.WA.catalog` is the slice for the currently selected
   city (read from localStorage 'wa:city' since city.js loads
   after this file). Same for curators. Without this filter, an
   offline visitor on the Riga or Helsinki city setting would
   see Tallinn picks bleed through.
   ============================================================ */
window.WA = window.WA || {};

const _waCity = (() => {
  try { return localStorage.getItem('wa:city') || 'tallinn'; }
  catch { return 'tallinn'; }
})();

window.WA._catalogAll = [
  {
    id:            "helsinkievents-3904",
    city:          "helsinki",
    title:         "History of Suomenlinna Church Exhibition",
    venue:         "Suomenlinnan kirkko",
    neighborhood:  "Suomenlinna",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Discover the history of Suomenlinna Church from the 18th century to the present day",
    handle:        "@helsinkievents",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "sober", "solo"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZPsg08tUmiSvg3eI_vlQ1txI1S6MY1e3zyMFrllD15K-5zti9yd0H22FRbO5Ch0OtyxbNLAi52YiU7LmKjRohQC-FbV6swp937OKV6ONxC_S6tXEEgesyeqgvndrMnZ63hg2qhXuAU9_IBQlw=s4800-w800",
    pin:           null
  },
  {
    id:            "otaniemievents-1781-speksijuhannus-midsummer-festi",
    city:          "helsinki",
    title:         "Speksijuhannus Midsummer Festival",
    venue:         "Vallittu, Kangasala",
    neighborhood:  "other",
    kind:          "festival",
    day:           null,
    time:          null,
    quote:         "Join the speksi-vibed people for a weekend of interspex activities, live music, and sauna.",
    handle:        "@otaniemievents",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "loud", "outdoors", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZM80M4pJxQBcl56mvwBVKLtzKEgGK9G30hlUuMCk2zbpPLy8KR2uTMavnTpQzw51pflQCyunXM7wejGqGDdivJyqTCpDCIkM-gsr6zS7c0R9ZBugHkkxvi92eepdNQBLix5iMGz2TbvxTwvmw=s4800-w800",
    pin:           null
  },
  {
    id:            "helsinkievents-3946-vantaan-kes-lava-concerts",
    city:          "helsinki",
    title:         "Vantaa Summer Stage Concerts",
    venue:         "Myyr York Park",
    neighborhood:  "Vantaa",
    kind:          "gig",
    day:           null,
    time:          null,
    quote:         "Free summer concert program in Vantaa",
    handle:        "@helsinkievents",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "outdoors", "loud"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZPRqxr4Pego1Tj3DwprV-uTkY9AVZp86gQSoCG99-M53edDFVVkvPOH1KwUBV_Y9jt0HiyZDXAHMkDiiBFLBHI3d7I0Pg63osVxbvBUnrSAMb5M-Lpx3mJoPFJaKx1O8cBY0-ZtelpW4pZV7ys=s4800-w800",
    pin:           null
  },
  {
    id:            "helsinkievents-3953-free-outdoor-dance-floor-at-am",
    city:          "helsinki",
    title:         "Free outdoor dance floor at Amos Rex",
    venue:         "Amos Rex",
    neighborhood:  "Lasipalatsi",
    kind:          "place",
    day:           null,
    time:          null,
    quote:         "Experience a unique outdoor dance floor with Bluetooth connection, where you can play your own music and dance for free.",
    handle:        "@helsinkievents",
    thumbInitials: "AR",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["outdoors", "social", "walk-up", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZNiLzWLgGY1n-h-dvS2Xv7Ux1CKKhiC5xsGiqcbXz-kUWU9mRUBQZDdMbOZulks3SK9VckI7cH5PSIp5Wu9HHcmn7ZM7zXOL-4_VCmFrnWeJrUDtSI4oBT-GobTu7-VsHZxUPKYbRzxewNqKw=s4800-w800",
    pin:           null
  },
  {
    id:            "helsinkievents-3972",
    city:          "helsinki",
    title:         "New exhibition on Helsinki's history",
    venue:         "Helsingin kaupungin museo",
    neighborhood:  "Kruununhaka",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Discover Helsinki's hidden meanings and surprising history at this new exhibition. Explore the city's significant moments and residents' lives through the centuries.",
    handle:        "@helsinkievents",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "sober", "solo"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOn4OYIU0_fskhlGKVsP89osh5wA5kPcxC9V1k1e7b3kL46rv7SS5Q09pWQfyDYaWxqBtOgv4WFj_-g2SAfltRUiqH7VLkJHfbuxvHjubrt4gqlisXXq7WFZoO3K-P2LX7FLpyvBVn9gOiwjyo=s4800-w800",
    pin:           null
  },
  {
    id:            "aaniwalli-drone-night",
    city:          "helsinki",
    title:         "Drone Night at Ääniwalli",
    venue:         "Ääniwalli",
    neighborhood:  "Kallio",
    kind:          "gig",
    day:           "Fri",
    time:          "21:00",
    quote:         "Forty minutes of uninterrupted drone. No encore, no chat.",
    handle:        "@jani.after",
    thumbInitials: "ÄW",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["loud", "indoors", "solo", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZP3BJFsXybGgIAtUq0cxOm1PQqhwBCVA3a41sR2rmIAs_1ahtbC86bYtdF8g5qbwGY7WDGmk5eQutdMi9dXBp1Kgtrz6gkGRNVpysV4CmcbZCFqu5HmsAMUI17fu7RtaSmW9qgO2g5Vf0TG7H4=s4800-w800",
    pin:           null
  },
  {
    id:            "baarikarpanen-late",
    city:          "helsinki",
    title:         "Baarikärpänen — late bar",
    venue:         "Baarikärpänen",
    neighborhood:  "Kallio",
    kind:          "club",
    day:           null,
    time:          "open late",
    quote:         "The bar that never asks why you are still here.",
    handle:        "@jani.after",
    thumbInitials: "BK",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["loud", "indoors", "social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZM5n97_Ko-0zgWYueHJ4ZZl845WhsyybumxqvYmPPldjZuR5soR2JzmtPcBtIIEE3VBsGFfaT9VOx7VB9e2_EDxOvQM5GM-aMDy7irCgUeE3Ycb1Y56RQx7lq5yZ3kHi0cqmVP5A6Qen8JehMo=s4800-w800",
    pin:           null
  },
  {
    id:            "kiasma-koho",
    city:          "helsinki",
    title:         "Koho — group show, Kiasma",
    venue:         "Kiasma",
    neighborhood:  "Töölö",
    kind:          "exhibition",
    day:           null,
    time:          "ongoing",
    quote:         "Finnish contemporary at its least obvious. Worth three visits.",
    handle:        "@jani.after",
    thumbInitials: "KO",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["quiet", "indoors", "solo", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOVueSbQ6NLPkWCgKChLLiivi9nq0gOJjfs6SxmQRYGQAwasfQO2pfG-el1qneIBjMGF7qnqj69UrzBnWURRej3q_ihDLpCg7dLQrF7LazEEtjg0bqLbtjgc6-5asb5iwWMM11HsJ4Xok1iA3Q=s4800-w612",
    pin:           null
  },
  {
    id:            "kaapelitehdas-vinyl",
    city:          "helsinki",
    title:         "Helsinki Vinyl Market",
    venue:         "Cable Factory",
    neighborhood:  "Ruoholahti",
    kind:          "market",
    day:           "Sat",
    time:          "10:00",
    quote:         "More crates than you have time for.",
    handle:        "@jani.after",
    thumbInitials: "VM",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["quiet", "indoors", "solo", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZNVYCjOIbm4rqF2jHoM5b1MtALpSq-MsERP3UEAhnsvb-76a59w6zOy0bHLhPkCSVyb7MRml7au6zIP22QbrF3Y7db3kRcSc7G-WoqrBmfJiWbGHsn045cKrJ_yIQ1Hy6p51u8T9ad3KoTf3XEn8njLtA=s4800-w800",
    pin:           null
  },
  {
    id:            "notboring_riga-4246",
    city:          "riga",
    title:         "Folk Techno & Electronic Stage at Holi Festival",
    venue:         "Wondersala",
    neighborhood:  "Centrs",
    kind:          "gig",
    day:           null,
    time:          null,
    quote:         "Escape the mainstream with international electronic artists and the unique folk techno duo Dyur, bringing a different vibe to the Holi Music Festival.",
    handle:        "@notboring_riga",
    thumbInitials: "HF",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "social", "drinks", "ticketed", "indoors"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGZCAVdQQErwYjy67dloDKHHlCTIhNbfAgHpbaAUmqZ6bhM57SXjBgXYn45Dcnklqtg86dyz0Q_6IAW2CUcPiveT92UixGcqNc=s4800-w800",
    pin:           null
  },
  {
    id:            "echogonewrong-1044869250397803",
    city:          "riga",
    title:         "Riga Photography Biennial 2026: 'everything you need to see is already in front of you'",
    venue:         "Gallery Space of the Riga Contemporary Art Space",
    neighborhood:  "Centrs",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "A solo exhibition by Priyageetha Dia, exploring the unseen.",
    handle:        "@echogonewrong",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZN-uE924JyxlTiEKqW8jAZ5lXWAg4p84aLyAyACW2i947InqRglpxfIDZwUBW54psOmbpud0jyNKsBXIychwsef61N7-2UpuTol4yGt6jcHlInJOXkbWVXqCm811ZxtMC5pnsfllgyV8mlpa8swq2XrgQ=s4800-w800",
    pin:           null
  },
  {
    id:            "echogonewrong-4834885832084220",
    city:          "riga",
    title:         "Live With/Think About by Kaspars Groševs",
    venue:         "Kim? Contemporary Art Centre",
    neighborhood:  "other",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "A small sketch of life: Kaspars Groševs' apartment available for short-term rent at Kim? Contemporary Art Centre.",
    handle:        "@echogonewrong",
    thumbInitials: "KG",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "solo", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZMv_57GuoMz0_cepNI4LYN0CiMewXWZg2pXtm_53X8duwyDXNfOsjvqgnYsJj1jideXTJ3M00ixir7Xxa4R6y50Eb-p_y87KrbsxhacLsvkvwg8vsZximrPluWsuZ1TyAJYB_QTgnUtkcNBpQA=s4800-w800",
    pin:           null
  },
  {
    id:            "echogonewrong-3711184685108563",
    city:          "riga",
    title:         "Macchiato XVI – Sauleszaķi festival",
    venue:         "Various venues",
    neighborhood:  "other",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Celebrating art across disciplines in a social atmosphere",
    handle:        "@echogonewrong",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "indoors"],
    pin:           null
  },
  {
    id:            "echogonewrong-3162528380960004",
    city:          "riga",
    title:         "Zoom In: Ecology Exhibition",
    venue:         "Riga Contemporary Art Space",
    neighborhood:  "other",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Explore the intersection of photography and ecology in this thought-provoking exhibition.",
    handle:        "@echogonewrong",
    thumbInitials: "AA",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "quiet", "solo"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZPwNE4ow8pHNFx8iJetrELbuHESx94BlqjskaQKc6IHW7lc8hVl-HAh0nSa2nGFAtHYyKqIiTK2J4SYA8Q6yFBgb7O6uGeI5pf_bu_DaLG1hXd5eGGyWAsq2_A3_OFmxBzTPnDxy0ktqpKGu3YUi8VreQ=s4800-w800",
    pin:           null
  },
  {
    id:            "echogonewrong-7759585672630940",
    city:          "riga",
    title:         "Stare Up At Me/Veries manī by Karlīna Mežecka",
    venue:         "Kim? Contemporary Art Centre",
    neighborhood:  "Centrs",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Experience Karlīna Mežecka's latest art exhibition at Kim? Contemporary Art Centre, inspired by Madonna's 'Don't Tell Me'. A unique visual exploration.",
    handle:        "@echogonewrong",
    thumbInitials: "KM",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZN94etgsrzoRQ9IV4Dbk8kDjTKr274TBh-6UxoarpEfO6MNc5tKswUPqrLqVSkkVwrtbQ3lmpjEuCaKmx2yz9NnFqeYCH0YtnDxsHn_taK8k7vKgTAIfqKxj1stvX4AaYyTjBY3PhgEKho4698=s4800-w800",
    pin:           null
  },
  {
    id:            "echogonewrong-4739255805995343",
    city:          "riga",
    title:         "Exhibition 'I want to Be Glue!' by Shana de Villiers",
    venue:         "TUR",
    neighborhood:  "other",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Step into TUR and meet the serpentine creature of 'I want to Be Glue!', a tender patchwork of textures and mythologies.",
    handle:        "@echogonewrong",
    thumbInitials: "SD",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "quiet", "solo"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZP4s9GNVOyxwbLmZ6n0W8_W2FFHqg1TkpbjAmqSYB7CWVphqIWZMMSim-itDXre1oVx9ItTm1EHIkaNppfa_7B02cZkCA4xgW5yBXdbXLs1sXz5iCWsQFxR94FF9YgzH3sJrSt3ddpYPLXOdw=s4800-w640",
    pin:           null
  },
  {
    id:            "echogonewrong-6652406191569123",
    city:          "riga",
    title:         "Within the Landscape / ainavā photo reportage",
    venue:         "Cultural and Historical Sites, Saldus Municipality",
    neighborhood:  "other",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Exploring landscape transformation through photography",
    handle:        "@echogonewrong",
    thumbInitials: "AG",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOPxH-cIb89jzJ2PhjXuvVlPq8kUpb9_eyHcnmrjozVVOgre2hfnEbcdKas1rLSmdSg4Rjl77g69zhIXT-_vO2AqsG2cuymHolxMB46jrLX59AbhBNbN9pe6tUXdSBPSuscL7-_tYU4w9uGtA=s4800-w800",
    pin:           null
  },
  {
    id:            "notboring_riga-4325",
    city:          "riga",
    title:         "Prusax's Personal Playlist",
    venue:         "Various venues",
    neighborhood:  "other",
    kind:          "sound performance",
    day:           null,
    time:          null,
    quote:         "Get a glimpse into Prusax's musical world with their personal playlist, a three-hour journey through a Saturday's soundtrack.",
    handle:        "@notboring_riga",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "sober"],
    pin:           null
  },
  {
    id:            "cafe-mimosa-guest-chef",
    city:          "riga",
    title:         "Guest chef night at Café Mimosa",
    venue:         "Café Mimosa",
    neighborhood:  "Centrs",
    kind:          "event",
    day:           "Fri",
    time:          "19:00",
    quote:         "They treat this kitchen like a stage. The guest chef nights are where Riga actually surprises you.",
    handle:        "@katestrelca",
    thumbInitials: "CM",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["quiet", "indoors", "social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqFcVOSyZg3ejZCFV6KaCHdvfzige_JwMI_KH8gGh2oe5vNezEGhlwPkxlDiV5oqw4Sits7e2S5IsPwBUlg0blYQ9WAX8Eo_fQI=s4800-w800",
    pin:           null
  },
  {
    id:            "kkc-experimental-night",
    city:          "riga",
    title:         "Experimental music night at KKC",
    venue:         "KKC",
    neighborhood:  "Āgenskalns",
    kind:          "gig",
    day:           "Fri",
    time:          "21:00",
    quote:         "Across the river and worth every bridge. KKC is where the real stuff happens.",
    handle:        "@katestrelca",
    thumbInitials: "KK",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["loud", "indoors", "social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOWHU8TsHemehC274RtOH1Izs2qgvgdGz4NjbCRAz2AoSaCTJEJLuLW9ZCL8g0_n4GRNKAG-H9VnxXUdJkEAPMcnGzfC3q8ysPtbEINAXt40mDrnlAMkTm21pgLiYljLxwW9d98dbBReaajN5g=s4800-w800",
    pin:           null
  },
  {
    id:            "skapis-queer-night",
    city:          "riga",
    title:         "Skapis — queer club night",
    venue:         "Skapis",
    neighborhood:  "Centrs",
    kind:          "club",
    day:           "Sat",
    time:          "23:00",
    quote:         "Community-built, community-run. Not a trend, a fact.",
    handle:        "@katestrelca",
    thumbInitials: "SK",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["loud", "indoors", "social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZNM2A14Apfau5RwdW2FytVfG06oH_SkETpjvj9MLhkNxWTSmX91houaxycCeK0nShnRc6_O2R79aoJa0zwero44NC9s9K0ci--BZcYBQOTfINxlGzFNoMuaEWVgXXnyQmXRL0mTErFzyvmQ5w=s4800-w800",
    pin:           null
  },
  {
    id:            "hanzas-perons-chamber",
    city:          "riga",
    title:         "Chamber concert at Hanzas Perons",
    venue:         "Hanzas Perons",
    neighborhood:  "Avoti",
    kind:          "gig",
    day:           "Sat",
    time:          "19:00",
    quote:         "A train hall that became one of the best concert rooms in the city. The acoustics earned it.",
    handle:        "@katestrelca",
    thumbInitials: "HP",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["quiet", "indoors", "sober", "ticketed"],
    imageUrl:      "https://commons.wikimedia.org/wiki/Special:FilePath/Hanzas_perons_(2).jpg",
    pin:           null
  },
  {
    id:            "kim-gallery-traces",
    city:          "riga",
    title:         "TRACES — Sabīne Skarule at Kim Gallery",
    venue:         "Kim Gallery",
    neighborhood:  "Centrs",
    kind:          "exhibition",
    day:           null,
    time:          "ongoing",
    quote:         "Design that asks questions instead of decorating walls.",
    handle:        "@katestrelca",
    thumbInitials: "KI",
    tonight:       false,
    thisWeek:      true,
    moodTags:      ["quiet", "indoors", "solo", "sober"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGM8ULFiIuI2BewIsbQljXdLeergMYIkVo7xtJEfQVz1R0jyXWf5dbWx6sLkPJiIY70nvmmRR0gUp7KI1VPuEvJuiUzf3U1IHY=s4800-w800",
    pin:           null
  },
  {
    id:            "sigmundtells-2516",
    city:          "tallinn",
    title:         "Film Club: Alcarràs Screening & Discussion",
    venue:         "Kino Artis",
    neighborhood:  "Vanalinn",
    kind:          "cinema",
    day:           null,
    time:          null,
    quote:         "Beyond the popcorn, engage with cinema that challenges. This isn't just a screening; it's a deep dive into the art.",
    handle:        "@sigmundtells",
    thumbInitials: "KA",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOA3LHY3ssL0o0kUpdCs0chlLUSRZ56fy6dkqTIkWSH10Ye_hJ0OmPIH6_lPLPxjcsMrYv0oU_hHyVcLR8NTbXBk0Kw2vInFhJPoG7INkKKkmbVVHGqTcBVDwTpxAuJJVPHihDtmGbKOOLu=s4800-w800",
    lat:           59.4331739,
    lng:           24.7516185,
    address:       "Estonia pst 9, 10143 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "giadafromgamma-1773810091",
    city:          "tallinn",
    title:         "English Performances at Kanuti Gildi SAAL",
    venue:         "Kanuti Gildi SAAL",
    neighborhood:  "Vanalinn",
    kind:          "theatre",
    day:           null,
    time:          null,
    quote:         "Kanuti Gildi SAAL consistently pushes boundaries, offering vital perspectives through its diverse performances. Reading keeps the city honest.",
    handle:        "@raul.reads",
    thumbInitials: "KG",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "ticketed"],
    imageUrl:      "https://commons.wikimedia.org/wiki/Special:FilePath/Kanuti_Gildi_Saal1.JPG?width=600",
    lat:           59.4385252,
    lng:           24.7460931,
    address:       "Pikk 20, 15059, Tallinn",
    pin:           null
  },
  {
    id:            "giadafromgamma-1776052882-egs-exhibition",
    city:          "tallinn",
    title:         "EGS Exhibition",
    venue:         "PoCo pop art museum",
    neighborhood:  "other",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Discover the vibrant works of Finnish street artist EGS at the PoCo pop art museum, a must-visit exhibition.",
    handle:        "@raul.reads",
    thumbInitials: "EG",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZNqTFskv4ZSwYTygztLLAkz4Hy18Hj1CKOCT-wGR1O4JyHm2gG5lRNwvs6oIOYhtwExCcy2kdAbVgDPz4-Khzwwnpxok0AL1_zAlf5j6Y6ZiXnPqBMETBpS9M6WcBtAfNizY3j2WgsRV-LDlMU=s4800-w800",
    lat:           59.4387603,
    lng:           24.7581548,
    address:       "Rotermanni tn 2, 10111 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "proeesti-4686",
    city:          "tallinn",
    title:         "Vera Polozkova Poetry Concert",
    venue:         "Various venues",
    neighborhood:  "other",
    kind:          "talk",
    day:           null,
    time:          null,
    quote:         "Experience the powerful voice of a generation's poetess as Vera Polozkova shares her poignant words on love, loss, and inner strength.",
    handle:        "@proeesti",
    thumbInitials: "VP",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "solo", "social", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZMzjgrPUJ3kK59LDbft3hIutvWl6e84Z4xZYw2_jVGE2eI36Uw226JR_OUOom260jDLzZGsWnDdUtS5CfmhVNLBVSVkLCp8xDDssfEtzWUTKmMaxD-ZlV7W7Y_7WSW1jDR_-mgkTVIwFCZw=s4800-w800",
    pin:           null
  },
  {
    id:            "paavli-kultuurivabrik-170265",
    city:          "tallinn",
    title:         "Nikki Nair (US)",
    venue:         "Paavli Kultuurivabrik",
    neighborhood:  "Põhja-Tallinn",
    kind:          "club",
    day:           null,
    time:          "23:00",
    quote:         "Nikki Nair is bringing his genre-bending, bass-heavy techno from the Atlanta underground to Tallinn. Get ready for experimental sounds and a night of unexpected dance music!",
    handle:        "@paavli",
    thumbInitials: "NN",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "drinks", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGcBRF0A399QyKRBV78aJ07OBVDftyuYeXeeXit5LL2yWKZl-7e6QJNYibz6mPabOW5mi5cqXyXCbnAJyCm0hMQv-MRBJ7x9Co=s4800-w800",
    lat:           59.4475957,
    lng:           24.704955,
    address:       "Paavli 7, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "paavli-kultuurivabrik-166091",
    city:          "tallinn",
    title:         "EYEHATEGOD, Childbeater, HUKK Live",
    venue:         "Paavli Kultuurivabrik",
    neighborhood:  "Põhja-Tallinn",
    kind:          "gig",
    day:           null,
    time:          "19:00",
    quote:         "Prepare for a sonic assault! Sludge metal legends Eyehategod bring their distorted, slow-burn chaos to Tallinn, supported by local heavyweights. Loud, weird, excellent.",
    handle:        "@paavli",
    thumbInitials: "EH",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "drinks", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGcBRF0A399QyKRBV78aJ07OBVDftyuYeXeeXit5LL2yWKZl-7e6QJNYibz6mPabOW5mi5cqXyXCbnAJyCm0hMQv-MRBJ7x9Co=s4800-w800",
    lat:           59.4475957,
    lng:           24.704955,
    address:       "Paavli 7, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "paavli-kultuurivabrik-177873",
    city:          "tallinn",
    title:         "Drew McDowall (UK) & Robert Nikolajev",
    venue:         "Paavli Kultuurivabrik",
    neighborhood:  "Põhja-Tallinn",
    kind:          "gig",
    day:           null,
    time:          "19:00",
    quote:         "Drew McDowall, a Coil alumnus, brings his uncompromising experimental soundscapes to Tallinn. Prepare for a night of truly boundary-pushing music.",
    handle:        "@paavli",
    thumbInitials: "DM",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGcBRF0A399QyKRBV78aJ07OBVDftyuYeXeeXit5LL2yWKZl-7e6QJNYibz6mPabOW5mi5cqXyXCbnAJyCm0hMQv-MRBJ7x9Co=s4800-w800",
    lat:           59.4475957,
    lng:           24.704955,
    address:       "Paavli 7, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "paavli-kultuurivabrik-169457",
    city:          "tallinn",
    title:         "Starbenders (US) Live",
    venue:         "Paavli Kultuurivabrik",
    neighborhood:  "Põhja-Tallinn",
    kind:          "gig",
    day:           null,
    time:          "19:00",
    quote:         "Loud, weird, excellent. This is rock’n’roll full of sparkle, chaos, and attitude – imagine David Bowie playing seven minutes in heaven with Debbie Harry!",
    handle:        "@paavli",
    thumbInitials: "SS",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "drinks", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGcBRF0A399QyKRBV78aJ07OBVDftyuYeXeeXit5LL2yWKZl-7e6QJNYibz6mPabOW5mi5cqXyXCbnAJyCm0hMQv-MRBJ7x9Co=s4800-w800",
    lat:           59.4475957,
    lng:           24.704955,
    address:       "Paavli 7, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "paavli-kultuurivabrik-184159",
    city:          "tallinn",
    title:         "Napalm Death, Master, The Brat, Goatburner",
    venue:         "Paavli Kultuurivabrik",
    neighborhood:  "Põhja-Tallinn",
    kind:          "gig",
    day:           null,
    time:          "19:00",
    quote:         "Grindcore pioneers and extreme music legends hit the stage. Loud, weird, excellent.",
    handle:        "@paavli",
    thumbInitials: "ND",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "drinks", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqGcBRF0A399QyKRBV78aJ07OBVDftyuYeXeeXit5LL2yWKZl-7e6QJNYibz6mPabOW5mi5cqXyXCbnAJyCm0hMQv-MRBJ7x9Co=s4800-w800",
    lat:           59.4475957,
    lng:           24.704955,
    address:       "Paavli 7, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "15-172435",
    city:          "tallinn",
    title:         "Feedback",
    venue:         "Von Krahli Teater",
    neighborhood:  "Vanalinn",
    kind:          "theatre",
    day:           null,
    time:          "19:00",
    quote:         "This experimental drama throws you into the heart of an uprising, exploring the visceral tension between rebellion and fear. A powerful piece from a cornerstone of Tallinn's fringe theatre.",
    handle:        "@vonkrahl",
    thumbInitials: "VT",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "social", "ticketed", "loud"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZMhEqjWu0jH2cU66hlOJjHW9bHAoVzWfjHlfmRdfSwst9nLvYy9QorNtsu8KAD5mTdwMjMJyWxhggJRQYlAVCB8J4l2H4VO1B9dEFyF8PY9PxN05scZnFY0OP8ENHXAlixwq0NCEYwwsk48GJ5xceVmnw=s4800-w800",
    lat:           59.4371803,
    lng:           24.7428101,
    address:       "Rataskaevu 10, 10123, Tallinn",
    pin:           null
  },
  {
    id:            "15-175394",
    city:          "tallinn",
    title:         "Cabaret Techno: The End is Just the Beginning",
    venue:         "Von Krahli Teater",
    neighborhood:  "Vanalinn",
    kind:          "theatre",
    day:           null,
    time:          "19:00",
    quote:         "A new era cabaret blending 1920s Berlin aesthetics with contemporary techno, dance, and social satire. Expect poetic words, grotesque humor, and physical theatre.",
    handle:        "@vonkrahl",
    thumbInitials: "VK",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZMhEqjWu0jH2cU66hlOJjHW9bHAoVzWfjHlfmRdfSwst9nLvYy9QorNtsu8KAD5mTdwMjMJyWxhggJRQYlAVCB8J4l2H4VO1B9dEFyF8PY9PxN05scZnFY0OP8ENHXAlixwq0NCEYwwsk48GJ5xceVmnw=s4800-w800",
    lat:           59.4371803,
    lng:           24.7428101,
    address:       "Rataskaevu 10, 10123, Tallinn",
    pin:           null
  },
  {
    id:            "15-177981",
    city:          "tallinn",
    title:         "Ooper: A Musical Production on Ambition",
    venue:         "Von Krahli teater",
    neighborhood:  "Vanalinn",
    kind:          "theatre",
    day:           null,
    time:          "20:00",
    quote:         "A musical production dissecting the destructive and inspiring force of ambition. Expect a powerful, experimental theatrical experience.",
    handle:        "@vonkrahl",
    thumbInitials: "VK",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "social", "ticketed"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZMhEqjWu0jH2cU66hlOJjHW9bHAoVzWfjHlfmRdfSwst9nLvYy9QorNtsu8KAD5mTdwMjMJyWxhggJRQYlAVCB8J4l2H4VO1B9dEFyF8PY9PxN05scZnFY0OP8ENHXAlixwq0NCEYwwsk48GJ5xceVmnw=s4800-w800",
    lat:           59.4371803,
    lng:           24.7428101,
    address:       "Rataskaevu 10, 10123, Tallinn",
    pin:           null
  },
  {
    id:            "sigmundtells-2558-exhibition-photography-in-powe",
    city:          "tallinn",
    title:         "Exhibition: Photography in Power: Making Worlds Visible",
    venue:         "Fotografiska",
    neighborhood:  "Telliskivi",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Explore the impactful 'Photography in Power' exhibition at Fotografiska. A visual journey into how images shape our world.",
    handle:        "@sigmundtells",
    thumbInitials: "FG",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "solo", "ticketed", "quiet"],
    imageUrl:      "https://commons.wikimedia.org/wiki/Special:FilePath/Fotografiska_tallinn_telliskivi_exterior1_-_2019.jpg?width=600",
    lat:           59.4383522,
    lng:           24.7284645,
    address:       "Telliskivi 60a/8, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "sigmundtells-2579-cinamon-moves-to-kosmos-cinema",
    city:          "tallinn",
    title:         "Cinamon moves to Kosmos cinema",
    venue:         "Kosmos cinema",
    neighborhood:  "Vanalinn",
    kind:          "cinema",
    day:           null,
    time:          null,
    quote:         "A new home for Cinamon, bringing horror movies to the screen",
    handle:        "@sigmundtells",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZME8_5mqStMFTDWmN-RFPSCjDEJXjX0B25xpzKUmrF0IxKnQIs5jn5Ylr4UCa65t3yHzbmzKIThiLVEmr7yPukxsUy2dx7jolExdu9Kb7fQPHNpMmNPE3xQ9AQtECVDSIEi2KB986FOC7Ptr2Y=s4800-w800",
    lat:           59.4280264,
    lng:           24.7440114,
    address:       "Pärnu mnt. 45, 10119 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "sigmundtells-2579-horror-movies-at-cinamon",
    city:          "tallinn",
    title:         "Horror movies at Cinamon",
    venue:         "Kosmos cinema",
    neighborhood:  "Vanalinn",
    kind:          "cinema",
    day:           null,
    time:          null,
    quote:         "Catch the latest horror hits like 'The Possession' and 'Behind the Scene of Reality'",
    handle:        "@sigmundtells",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZME8_5mqStMFTDWmN-RFPSCjDEJXjX0B25xpzKUmrF0IxKnQIs5jn5Ylr4UCa65t3yHzbmzKIThiLVEmr7yPukxsUy2dx7jolExdu9Kb7fQPHNpMmNPE3xQ9AQtECVDSIEi2KB986FOC7Ptr2Y=s4800-w800",
    lat:           59.4280264,
    lng:           24.7440114,
    address:       "Pärnu mnt. 45, 10119 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "sigmundtells-2583-outdoor-screening-of-2026-worl",
    city:          "tallinn",
    title:         "Outdoor screening of 2026 World Cup",
    venue:         "Paavli Kultuurivabrik",
    neighborhood:  "Telliskivi",
    kind:          "arts centre",
    day:           null,
    time:          null,
    quote:         "Experience the World Cup in a cultural setting",
    handle:        "@sigmundtells",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["outdoors", "social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOjCxoHHmaizeNkH9YHUQYuO4JB7i-Jh4w5eazPPl3KgBlj0ha9jJGG6xsOBVDbV87341YR6eEdJB5RQ6EnbRoKx0Ko9a5jtEZOW1LlxHCkTecUH1321sFOSGMnQs1cN-Goa3GDOhMFJgYZyA=s4800-w800",
    lat:           59.4475874,
    lng:           24.7049709,
    address:       "Paavli tn 7, 10412 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "sigmundtells-2583-sports-bar-with-2026-world-cup",
    city:          "tallinn",
    title:         "Sports bar with 2026 World Cup",
    venue:         "Beer Garden",
    neighborhood:  "other",
    kind:          "bar",
    day:           null,
    time:          null,
    quote:         "Watch the World Cup in a lively beer garden",
    handle:        "@sigmundtells",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "drinks", "loud"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZO8ktqaZRYxCFs2PJQzT2jNTOgJhM6An9cqUyzkKamT1ux00yFXcTBk7M_bIWjcUvdsKSd-wxpXM1-Qveomu9jZ3OSlwCBJm6JZ_oz_s5RlyT1dln2LOEAup6ltZspNj9ZrAFgSAGA7Ilg5sA=s4800-w800",
    lat:           59.4382258,
    lng:           24.7519333,
    address:       "Inseneri tn 1, 10111 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "sigmundtells-2585",
    city:          "tallinn",
    title:         "Rat Chat podcast launch",
    venue:         "Various venues",
    neighborhood:  "other",
    kind:          "talk",
    day:           null,
    time:          null,
    quote:         "Tune in for unfiltered conversations on human behavior and social quirks",
    handle:        "@sigmundtells",
    thumbInitials: "EA",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["sober", "solo"],
    pin:           null
  },
  {
    id:            "uus-laine",
    city:          "tallinn",
    title:         "Uus Laine — late DJ bar, no lineup",
    venue:         "Uus Laine",
    neighborhood:  "Põhja-Tallinn",
    kind:          "club",
    day:           "Sat",
    time:          "23:00",
    quote:         "After midnight, no lineup, no regrets.",
    handle:        "@hel.nocturnes",
    thumbInitials: "UL",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["loud", "indoors", "social", "drinks"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZNcPryVRhLWc3qjb9J8UzYGGuK9ea8VBLOucXCEq2cVmLjBFwtJCsfI3bsdy6sW1W4e3K4Wtn4fkNM-AMPhAFYhhlo2KFmr75-cwybk6UibSfAY0lndNU24zDU3ujnNt-4fB5dxSDdYQce-P1dOCRV9KQ=s4800-w800",
    lat:           59.4414205,
    lng:           24.7381887,
    address:       "Kopli 4, 10412, Tallinn",
    pin:           null
  },
  {
    id:            "turntable-tallinn",
    city:          "tallinn",
    title:         "Turntable Tallinn",
    venue:         "Turntable Tallinn",
    neighborhood:  "Telliskivi",
    kind:          "record store",
    day:           null,
    time:          "open daily",
    quote:         "Their B-side curation is unmatched.",
    handle:        "@mattias.v",
    thumbInitials: "TT",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "walk-up"],
    imageUrl:      "https://lh3.googleusercontent.com/place-photos/AJRVUZOySM8zwS3zqhWqPH2dgDIzFWYjCRppqxBCiQbzrYX1FA2gh9wQ0FwWhHTCP7wMAL4XoiRcZ3TbdMEjSuGTKaQBNeUXWnoTucklbYb8zuFx9PqY90AefVLS4psOlMyMKHlhS4SFO5T4FPCW=s4800-w800",
    lat:           59.440257,
    lng:           24.7335355,
    address:       "Telliskivi tn 60/2, 10412 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "vota-voi-jata",
    city:          "tallinn",
    title:         "Take or Leave",
    venue:         "Võta või Jäta",
    neighborhood:  "Põhja-Tallinn",
    kind:          "thrift",
    day:           null,
    time:          "Wed–Sun",
    quote:         "Where Tallinn's old paperbacks rest.",
    handle:        "@mattias.v",
    thumbInitials: "VJ",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "walk-up"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqHNrqTi8puiI6u2_z03B3H2QJWbcnfGdAvz14CEo0x0wOKrFqwD5S_IKARcx-iQmaSqAxSRcH2LMByUbRkHdXl-G8h9dxq_LIE=s4800-w800",
    lat:           59.4298591,
    lng:           24.7592864,
    address:       "Liivalaia tn 36, 10132 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "koogi-galerii",
    city:          "tallinn",
    title:         "Köögi Galerii",
    venue:         "Köögi Galerii",
    neighborhood:  "Kalamaja",
    kind:          "gallery",
    day:           null,
    time:          "ongoing",
    quote:         "A gallery in someone's actual kitchen.",
    handle:        "@kaisa.writes",
    thumbInitials: "KG",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "walk-up"],
    imageUrl:      "https://lh3.googleusercontent.com/places/ANXAkqERJ6ZZBqVXn_Qo2EOervVacYLHixyXbT47hJNDhzz1gfE1xeuemtTivQ0TVcWA6Q00Xm2x1ajJWYi1qiF89_u_5OyT1NUy6hs=s4800-w800",
    lat:           59.4451815,
    lng:           24.7285136,
    address:       "Salme tn 19, 10413 Tallinn, Estonia",
    pin:           null
  },
  {
    id:            "feminine-power",
    city:          "tallinn",
    title:         "Feminine power — group show",
    venue:         "Kumu",
    neighborhood:  "Kadriorg",
    kind:          "exhibition",
    day:           null,
    time:          null,
    quote:         "Worth a second visit.",
    handle:        "@kaisa.writes",
    thumbInitials: "FP",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["quiet", "indoors", "solo", "ticketed"],
    imageUrl:      "https://commons.wikimedia.org/wiki/Special:FilePath/Le_KUMU%2C_mus%C3%A9e_dart_estonien_%28Tallinn%29_%287643108702%29.jpg?width=600",
    lat:           59.4353156,
    lng:           24.7981512,
    address:       "Laagna tee, 11413, Tallinn",
    pin:           null
  },
  {
    id:            "afishavilnius-12139",
    city:          "vilnius",
    title:         "Rathayatra Festival",
    venue:         "Various venues",
    neighborhood:  "other",
    kind:          "event",
    day:           null,
    time:          null,
    quote:         "Experience the vibrant Rathayatra Festival, a visual treat you won't want to miss. Get ready for a spectacular celebration!",
    handle:        "@afishavilnius",
    thumbInitials: "PA",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["social", "outdoors", "loud"],
    pin:           null
  },
  {
    id:            "afishavilnius-12193-toxic-garden-exhibition-at-art",
    city:          "vilnius",
    title:         "Toxic Garden exhibition at Artifex Gallery",
    venue:         "Artifex Gallery",
    neighborhood:  "Senamiestis",
    kind:          "exhibition",
    day:           null,
    time:          "12:00",
    quote:         "Explore a mutant 'garden' of ceramic objects at Artifex Gallery, featuring guided tours with the artist.",
    handle:        "@afishavilnius",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "sober", "quiet", "solo"],
    pin:           null
  },
  {
    id:            "afishavilnius-12221",
    city:          "vilnius",
    title:         "Lithuanian-Jewish Art from the Shmuel Tatz Collection",
    venue:         "M. K. Čiurlionis House",
    neighborhood:  "Senamiestis",
    kind:          "exhibition",
    day:           null,
    time:          "11:00-16:00",
    quote:         "Explore the connection between painting and music, memory and history, through works by modernist masters like Picasso and Chagall.",
    handle:        "@afishavilnius",
    thumbInitials: "XX",
    tonight:       false,
    thisWeek:      false,
    moodTags:      ["indoors", "sober", "quiet", "solo"],
    pin:           null
  }
];

/* Filter the all-cities list to the active city. supabase.js will
   replace this with live data once the network responds, but the
   filter ensures the offline fallback respects the city setting. */
if (window.WA.when) window.WA.when.stampAll(window.WA._catalogAll);
window.WA.catalog = window.WA._catalogAll.filter(e => e.city === _waCity);

window.WA._curatorsAll = [
  {
    handle:  "@ayyevents",
    name:    "AYY Events",
    city:    "helsinki",
    tagline: "Aalto Student Union — events open to all.",
    bio:     "Aalto Yliopiston Ylioppilaskunta (AYY) official events channel. Student-run but the bigger nights — concerts, sitsit, parties at Smökki — are open to outside visitors too."
  },
  {
    handle:  "@hel_today",
    name:    "Helsinki Today",
    city:    "helsinki",
    tagline: "Events from the official Helsinki open-data calendar.",
    bio:     "Aggregated picks from the City of Helsinki Linked Events API — the same source that powers tapahtumat.hel.fi, myhelsinki.fi/helsinki-event-calendar, and helsinki.today. WanderAlt's editorial filter only keeps events that fit the alternative-culture brief."
  },
  {
    handle:  "@helsinkievents",
    name:    "Helsinki Events",
    city:    "helsinki",
    tagline: "Events across Helsinki, daily.",
    bio:     "Public Telegram channel aggregating events across Helsinki — gigs, exhibitions, club nights, talks. Curated picks flow through WanderAlt's editorial filter."
  },
  {
    handle:  "@jani.after",
    name:    "Jani",
    city:    "helsinki",
    tagline: "Late nights and loud rooms in Helsinki.",
    bio:     "Catches the shows nobody writes about. Usually found somewhere in Kallio after midnight."
  },
  {
    handle:  "@otaniemievents",
    name:    "Otaniemi Events",
    city:    "helsinki",
    tagline: "What's on in Otaniemi & Espoo.",
    bio:     "Events channel for Otaniemi and the Espoo side of greater Helsinki — Aalto campus events, student-run parties, openings."
  },
  {
    handle:  "@AfishaRiga",
    name:    "Afisha Riga",
    city:    "riga",
    tagline: "Latvia's cultural calendar in Russian.",
    bio:     ""
  },
  {
    handle:  "@echogonewrong",
    name:    "Echo Gone Wrong",
    city:    "riga",
    tagline: "Baltic art press from Riga.",
    bio:     ""
  },
  {
    handle:  "@hanzasperons",
    name:    "Hanzas Perons",
    city:    "riga",
    tagline: "Contemporary concert hall in New Hanza.",
    bio:     ""
  },
  {
    handle:  "@katestrelca",
    name:    "Kate Strelca",
    city:    "riga",
    tagline: "Riga without the tourist trail.",
    bio:     "Runs @notboring_riga — curated news, events and places since before it was fashionable to care about the city. Finds the good ones early."
  },
  {
    handle:  "@kinobize",
    name:    "Kino Bize",
    city:    "riga",
    tagline: "Art-house in the heart of Riga.",
    bio:     "Riga's leading art-house cinema. Baltic docs, Central European cinema, retrospectives, festival films, and the occasional midnight oddity."
  },
  {
    handle:  "@kseniakamikaza",
    name:    "Ksenia Kamikaza",
    city:    "riga",
    tagline: "Riga's electronic underground.",
    bio:     "DJ, producer, founder of UNDER Festival and Platz Für Tanz label, host of Intelligent Beats on Radio Naba since 2003. Curates the city's long-running techno / IDM / ambient circuit."
  },
  {
    handle:  "@notboring_riga",
    name:    "Kate",
    city:    "riga",
    tagline: "curated news, events and places",
    bio:     "Runs the not boring → Riga channel. Curates the best of Riga culture with a sharp eye for good design and authentic experiences."
  },
  {
    handle:  "@splendidpalace",
    name:    "Splendid Palace",
    city:    "riga",
    tagline: "Riga's grand art-house, since 1923.",
    bio:     "European Film Academy partner. Auteur cinema, festival favourites, Baltic premieres, and the occasional strange event in a very ornate room."
  },
  {
    handle:  "@udgstriga",
    name:    "Underground Station",
    city:    "riga",
    tagline: "Forward-thinking electronic music in Riga.",
    bio:     "Riga collective broadcasting parties, raves, and DIY electronic events from the city's underground."
  },
  {
    handle:  "@discovery",
    name:    "Discovery",
    city:    "tallinn",
    tagline: "Surfaced by external search — not yet curated.",
    bio:     "Picks marked with @discovery come from external searches (Google Places). They are not vouched for by a curator and stay hidden from the main feed until an editor reviews them."
  },
  {
    handle:  "@hel.nocturnes",
    name:    "Hel",
    city:    "tallinn",
    tagline: "After midnight the city reveals itself.",
    bio:     "DJ, occasionally and reluctantly described as underground. More importantly: knows where the good after-parties are. Moved from Helsinki to Tallinn in 2021 for reasons she summarises as cheaper and weirder. Has a strict policy of never listing anything that still has a queue at 23:30. Posts roughly once a week, always about things happening that same night. Does not respond to booking enquiries via Telegram."
  },
  {
    handle:  "@kaisa.writes",
    name:    "Kaisa",
    city:    "tallinn",
    tagline: "Go to the opening. Skip the opening speech.",
    bio:     "Art critic turned occasional curator, based in Tallinn since 2018. Contributes to a couple of art magazines nobody outside the Baltics has heard of, which is how she likes it. Particular about what she calls institutional sincerity—the difference between a museum that shows difficult work because it believes in it and one that shows it for the press release. If she recommends an opening, the work is worth arriving early for."
  },
  {
    handle:  "@mattias.v",
    name:    "Mattias",
    city:    "tallinn",
    tagline: "The best things in a city are not listed anywhere.",
    bio:     "Swedish-Estonian. Has lived in Tallinn long enough to have a considered opinion about every vinyl shop within walking distance of the Old Town. Works in graphic design, which he treats as a day job for supporting a record habit. Finds thrift stores professionally interesting and personally ruinous. Reads widely in architecture and photography. Has never recommended a place without visiting it at least twice first. Suspicious of novelty; enthusiastic about permanence."
  },
  {
    handle:  "@paavli",
    name:    "Paavli Kultuurivabrik",
    city:    "tallinn",
    tagline: "Loud, weird, excellent.",
    bio:     "Former industrial space in Põhja-Tallinn turned into a venue for punk, metal, electronic, and experimental music. Programme via Fienta."
  },
  {
    handle:  "@proeesti",
    name:    "proEesti",
    city:    "tallinn",
    tagline: "Estonian news & events feed",
    bio:     "Public Telegram channel covering events, culture, and news across Estonia."
  },
  {
    handle:  "@raul.reads",
    name:    "Raul",
    city:    "tallinn",
    tagline: "Reading keeps the city honest.",
    bio:     "Teaches cultural studies at Tallinn University, when not arguing about slow cinema in the back row of Sõprus. Has a particular fondness for lectures that end without conclusions. Reads two newspapers a day—one in Estonian, one in Russian—and considers this basic hygiene. His picks run toward talks, symposia, and evenings where the format is unclear but the thinking is rigorous. Believes the best event is one where you leave slightly less certain of your opinions."
  },
  {
    handle:  "@sigmundtells",
    name:    "Sigmund",
    city:    "tallinn",
    tagline: "The underground isn't a place. It's a posture.",
    bio:     "Grew up between Tartu and Riga. Spent three years running a noise collective out of a converted tram depot in Kalamaja before the building was turned into co-working. Writes a weekly Telegram channel about experimental music in the Baltics and occasionally ruins dinner parties with thoughts about the semiotics of feedback. Currently lives above a kebab shop near Balti jaam. Has seen Sveta Baar survive three ownership changes and remain stubbornly itself."
  },
  {
    handle:  "@telliskivi",
    name:    "Telliskivi Creative City",
    city:    "tallinn",
    tagline: "Where Tallinn gets creative.",
    bio:     "Tallinn's main creative hub: gigs, markets, exhibitions, dance, theatre, film clubs, flea markets. All under one roof in Põhja-Tallinn."
  },
  {
    handle:  "@vonkrahl",
    name:    "Von Krahl Theatre",
    city:    "tallinn",
    tagline: "Experimental theatre, since 1992.",
    bio:     "Tallinn's longest-running independent theatre. Avant-garde productions, TMW events, alternative performances. Programme via Fienta."
  },
  {
    handle:  "@afishavilnius",
    name:    "Afisha Vilnius",
    city:    "vilnius",
    tagline: "Events across Vilnius, daily.",
    bio:     "Public Telegram channel aggregating events across Vilnius — concerts, exhibitions, club nights, talks (Russian-language). Curated picks flow through WanderAlt's editorial filter."
  },
  {
    handle:  "@ra_vilnius",
    name:    "Resident Advisor",
    city:    "vilnius",
    tagline: "Club nights and raves, Vilnius.",
    bio:     "Electronic events listed on Resident Advisor (ra.co) for Vilnius — techno, club nights, raves, experimental live. WanderAlt's editorial filter keeps the ones that fit the alternative-culture brief."
  }
];

window.WA.curators = window.WA._curatorsAll.filter(c => c.city === _waCity);

window.WA.past = [
  { id: "skweee-sveta-baar", title: "Skweee night at Sveta Baar", date: "Apr 11" },
  { id: "algirdas-seskus", title: "Algirdas Šeškus — retrospective", date: "Mar 22" },
  { id: "late-winter-readings", title: "Late winter readings, Lugemik", date: "Mar 8" }
];

/* Static Places (venues) seed — alt-culture spots used as the offline
   fallback when supabase.js can't reach the venues table. Live data
   (window.WA.venues, filtered to WA.VENUE_KINDS) replaces this on a
   successful fetch. Real venues only. */
window.WA._venuesAll = [
  /* Tallinn */
  { id:"v-biitme",    city:"tallinn",  name:"Biit Me Record Store",         neighborhood:"Kesklinn",      kind:"record store", lat:59.4338, lng:24.7536, imageUrl:null, imageAttr:null, website:"https://biitme.ee", facebook:"https://facebook.com/biitmerecordstore", instagram:"https://instagram.com/biitme_recordstore" },
  { id:"v-lugemik",   city:"tallinn",  name:"Lugemik",                      neighborhood:"Kalamaja",      kind:"bookshop",     lat:59.4427, lng:24.7384, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:"https://instagram.com/lugemik" },
  { id:"v-ekkm",      city:"tallinn",  name:"EKKM",                         neighborhood:"Põhja-Tallinn", kind:"arts centre",  lat:59.4486, lng:24.7472, imageUrl:null, imageAttr:null, website:"https://ekkm.ee", facebook:"https://facebook.com/ekkm.ee", instagram:"https://instagram.com/ekkm_tallinn" },
  { id:"v-kaiart",    city:"tallinn",  name:"Kai Art Center",               neighborhood:"Noblessner",    kind:"gallery",      lat:59.4515, lng:24.7727, imageUrl:null, imageAttr:null, website:"https://kai.center", facebook:null, instagram:"https://instagram.com/kaiartcenter" },
  { id:"v-sveta",     city:"tallinn",  name:"Sveta Baar",                   neighborhood:"Telliskivi",    kind:"club",         lat:59.4366, lng:24.7320, imageUrl:null, imageAttr:null, website:null, facebook:"https://facebook.com/svetabaar", instagram:null },
  { id:"v-fotografiska",city:"tallinn",name:"Fotografiska",                 neighborhood:"Telliskivi",    kind:"gallery",      lat:59.4372, lng:24.7338, imageUrl:null, imageAttr:null, website:"https://fotografiska.com/tallinn", facebook:null, instagram:"https://instagram.com/fotografiska.tallinn" },
  /* Helsinki */
  { id:"v-stupido",   city:"helsinki", name:"Stupido Records",              neighborhood:"Kallio",        kind:"record store", lat:60.1841, lng:24.9501, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:"https://instagram.com/stupidorecords" },
  { id:"v-nide",      city:"helsinki", name:"Nide",                         neighborhood:"Punavuori",     kind:"bookshop",     lat:60.1626, lng:24.9402, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  { id:"v-aaniwalli", city:"helsinki", name:"Ääniwalli",                    neighborhood:"Vallila",       kind:"club",         lat:60.1959, lng:24.9540, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  { id:"v-kiasma",    city:"helsinki", name:"Kiasma",                       neighborhood:"Töölö",         kind:"gallery",      lat:60.1719, lng:24.9362, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  /* Riga */
  { id:"v-kkc",       city:"riga",     name:"Kaņepes Kultūras centrs",      neighborhood:"Centrs",        kind:"community",    lat:56.9512, lng:24.1146, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  { id:"v-kim",       city:"riga",     name:"Kim? Contemporary Art Centre", neighborhood:"Centrs",        kind:"gallery",      lat:56.9430, lng:24.1010, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  { id:"v-roberts",   city:"riga",     name:"Robert's Books",               neighborhood:"Centrs",        kind:"bookshop",     lat:56.9489, lng:24.1180, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  /* Vilnius — static seed for Places mode offline fallback. Live data
     replaces this once Vilnius is added to ingest-osm's CITIES map (cloud
     step — not yet deployed). Real, verified venues only. Coords are
     approximate (street-level, central Vilnius) placeholders for the
     offline map; ingest-osm backfills exact OSM coords. Website/social
     fields are set only where independently verified, else null. */
  { id:"v-loftas",    city:"vilnius",  name:"Menų fabrikas Loftas",          neighborhood:"Naujamiestis",  kind:"arts centre",  lat:54.6755, lng:25.2638, imageUrl:null, imageAttr:null, website:"https://menufabrikas.lt", facebook:"https://facebook.com/loftasvilnius", instagram:"https://instagram.com/menufabrikas" },
  { id:"v-kablys",    city:"vilnius",  name:"Kablys",                        neighborhood:"Naujamiestis",  kind:"club",         lat:54.6720, lng:25.2790, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  { id:"v-opium",     city:"vilnius",  name:"Opium Club",                    neighborhood:"Naujamiestis",  kind:"club",         lat:54.6843, lng:25.2790, imageUrl:null, imageAttr:null, website:"https://opiumclub.lt", facebook:"https://facebook.com/Opiumas", instagram:null },
  { id:"v-cac",       city:"vilnius",  name:"Contemporary Art Centre (ŠMC)", neighborhood:"Senamiestis",   kind:"gallery",      lat:54.6790, lng:25.2855, imageUrl:null, imageAttr:null, website:"https://cac.lt", facebook:null, instagram:"https://instagram.com/cacvilnius" },
  { id:"v-skalvija",  city:"vilnius",  name:"Skalvija Cinema",               neighborhood:"Naujamiestis",  kind:"cinema",       lat:54.6905, lng:25.2720, imageUrl:null, imageAttr:null, website:"https://skalvija.lt", facebook:null, instagram:null },
  { id:"v-mint",      city:"vilnius",  name:"Mint Vinetu",                   neighborhood:"Senamiestis",   kind:"bookshop",     lat:54.6820, lng:25.2860, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null },
  { id:"v-vinyloteka",city:"vilnius",  name:"Vinyloteka",                    neighborhood:"Senamiestis",   kind:"record store", lat:54.6880, lng:25.2845, imageUrl:null, imageAttr:null, website:null, facebook:null, instagram:null }
];
window.WA.venues = window.WA._venuesAll.filter(v => v.city === _waCity);
