/* Ukrainian. English phrase → Ukrainian; see i18n.js. Generated by .scripts/build-lang.py from lang/phrases.tsv
   and lang/patterns.tsv: edit those, not this file. */
window.WA = window.WA || {}; window.WA.dict = window.WA.dict || {};
window.WA.dict.uk = {
 "exact": {
  "Not found": "Не знайдено",
  "Skip to content": "Перейти до вмісту",
  "That page has closed down.": "Цю сторінку закрито.",
  "Listings expire, which is normal. Here is what's on instead.": "Оголошення застарівають, це нормально. Ось що відбувається натомість.",
  "Tonight in Tallinn": "Сьогодні ввечері в Таллінні",
  "The week": "Тиждень",
  "Now": "Зараз",
  "Map": "Мапа",
  "Guide": "Гід",
  "Saved": "Збережене",
  "That page is not here.": "Такої сторінки тут немає.",
  "You": "Профіль",
  "About": "Про проєкт",
  "We read the sources so you don't open nine tabs.": "Ми читаємо джерела, щоб вам не довелося відкривати дев’ять вкладок.",
  "Independent culture in Tallinn. A time, a walk and a source on every listing.": "Незалежна культура Таллінна. Кожна подія має час, шлях пішки і джерело.",
  "What this is": "Що це",
  "The week as a calendar": "Тиждень у вигляді календаря",
  "Subscribe once and the week stays current. Your calendar re-reads it twice a day. Nothing is pushed and no account is needed.": "Підпишіться один раз, і тиждень завжди буде актуальним. Ваш календар оновлює його двічі на день. Нічого не надсилається, обліковий запис не потрібен.",
  "Privacy": "Конфіденційність",
  "Venue data and removal": "Дані про місця та видалення",
  "Terms, briefly": "Умови коротко",
  "How WanderAlt reads Tallinn's sources, what it stores, and the calendar feed.": "Як WanderAlt читає джерела Таллінна, що зберігає і як працює календарна стрічка.",
  "Filters": "Фільтри",
  "Back": "Назад",
  "Share": "Поділитися",
  "Close": "Закрити",
  "The week in Tallinn's independent scene, day by day, with a walking distance on every listing.": "Тиждень незалежної сцени Таллінна по днях, з відстанню пішки для кожної події.",
  "Show on the map": "Показати на мапі",
  "Clear": "Очистити",
  "Where": "Де",
  "When": "Коли",
  "Tonight": "Сьогодні ввечері",
  "What": "Що",
  "What's on tonight": "Що сьогодні ввечері",
  "Search": "Пошук",
  "All": "Усе",
  "Events": "Події",
  "Places": "Місця",
  "Tomorrow": "Завтра",
  "Weekend": "Вихідні",
  "This week": "Цього тижня",
  "In view": "У кадрі",
  "Reading the sources": "Читаємо джерела",
  "Tonight's events and the places open now in Tallinn, on one map, sorted by walking time.": "Сьогоднішні події та відкриті зараз місця Таллінна на одній мапі, за часом пішки.",
  "Show": "Показати",
  "Show where I am": "Показати, де я",
  "Picked places in Tallinn. Not every bar, only the ones worth the walk.": "Вибрані місця Таллінна. Не кожен бар, лише ті, до яких варто пройтися.",
  "Open now": "Відчинено зараз",
  "Picked places in Tallinn: record shops, bookshops, galleries, thrift shops, small cinemas, clubs and theatres, with what's open now.": "Вибрані місця Таллінна: крамниці платівок і книгарні, галереї, секонд-хенди, невеликі кінотеатри, клуби й театри, і що відчинено зараз.",
  "Your saves, follows, alerts and settings.": "Збережене, підписки, сповіщення і налаштування.",
  "Route": "Маршрут",
  "An evening on foot: a few stops, with walking times and where each one comes from.": "Вечір пішки: кілька зупинок, час у дорозі та джерело кожної.",
  "Back to Now": "Назад до «Зараз»",
  "Your shortlist of events and places. Stays in this browser, works signed out.": "Ваш список подій і місць. Зберігається в цьому браузері й працює без входу.",
  "One source's listings in Tallinn.": "Події одного джерела в Таллінні.",
  "Listings": "Події",
  "Sources": "Джерела",
  "Sign in": "Увійти",
  "Email": "Електронна пошта",
  "Use a password instead": "Використати пароль",
  "Cancel": "Скасувати",
  "Email me a link": "Надіслати посилання",
  "We sent a sign-in link to": "Ми надіслали посилання для входу на",
  ". Open it on this device to finish.": ". Відкрийте його на цьому пристрої, щоб завершити.",
  "The email has a code": "У листі є код",
  "Code from the email": "Код із листа",
  "Use another email": "Інша адреса",
  "Verify": "Підтвердити",
  "Password": "Пароль",
  "Email me a link instead": "Надіслати посилання на пошту",
  "Forgot password?": "Забули пароль?",
  "Create account": "Створити обліковий запис",
  "Already have an account? Sign in": "Уже маєте обліковий запис? Увійти",
  "Enter your email and we'll send a reset link.": "Введіть пошту, і ми надішлемо посилання для скидання.",
  "Back to sign in": "Назад до входу",
  "Send reset link": "Надіслати посилання для скидання",
  "Choose a new password for your account.": "Виберіть новий пароль для облікового запису.",
  "New password": "Новий пароль",
  "Update password": "Оновити пароль",
  "Your password": "Ваш пароль",
  "At least 6 characters": "Щонайменше 6 символів",
  "Sign in or create an account": "Увійдіть або створіть обліковий запис",
  "Enter": "Увійти",
  "Enter your email address.": "Введіть адресу пошти.",
  "Sending…": "Надсилання…",
  "Could not send the link. Try again.": "Не вдалося надіслати посилання. Спробуйте ще раз.",
  "Network error.": "Помилка мережі.",
  "Check your email": "Перевірте пошту",
  "Enter the digits from the email.": "Введіть цифри з листа.",
  "Checking…": "Перевірка…",
  "That code did not work. Try again or use the link.": "Цей код не підійшов. Спробуйте ще раз або скористайтеся посиланням.",
  "Please fill in both fields.": "Заповніть обидва поля.",
  "Signing in…": "Вхід…",
  "Invalid email or password.": "Неправильна пошта або пароль.",
  "Please enter your email.": "Введіть пошту.",
  "Password must be at least 6 characters.": "Пароль має містити щонайменше 6 символів.",
  "Creating account…": "Створення облікового запису…",
  "Check your inbox to confirm your email, then sign in.": "Перевірте пошту, підтвердьте адресу, а потім увійдіть.",
  "Sign-up failed. Try again.": "Не вдалося зареєструватися. Спробуйте ще раз.",
  "Reset password": "Скинути пароль",
  "Check your inbox — reset link sent.": "Перевірте пошту — посилання для скидання надіслано.",
  "Something went wrong.": "Щось пішло не так.",
  "Set new password": "Задати новий пароль",
  "Session expired. Request a new reset link.": "Сеанс завершився. Запросіть нове посилання для скидання.",
  "Updating…": "Оновлення…",
  "Password updated. You are now signed in.": "Пароль оновлено. Ви увійшли.",
  "Update failed.": "Не вдалося оновити.",
  "Select city": "Виберіть місто",
  "Coming soon": "Незабаром",
  "Walking from": "Пішки від",
  "Live": "Триває",
  "Loading map…": "Завантаження мапи…",
  "Could not load the original description.": "Не вдалося завантажити оригінальний опис.",
  "Try again": "Спробувати ще раз",
  "The source filed no description beyond the title.": "Джерело не дало опису, крім назви.",
  "Read the full source": "Читати джерело повністю",
  "Loading source excerpt…": "Завантаження уривка з джерела…",
  "The venue": "Місце",
  "This has ended.": "Це вже завершилося.",
  "Open the listing": "Відкрити оголошення",
  "Calendar": "Календар",
  "Walk there": "Піти пішки",
  "Address": "Адреса",
  "Walking directions": "Маршрут пішки",
  "Flag a problem": "Повідомити про проблему",
  "What is wrong": "Що не так",
  "Note, optional": "Примітка, необов’язково",
  "Send": "Надіслати",
  "Picked places within 10 minutes on foot.": "Вибрані місця за 10 хвилин пішки.",
  "Plan the next hours from here": "Спланувати найближчі години звідси",
  "This venue is listed as closed.": "Це місце позначене як закрите.",
  "Check with the venue before you go.": "Уточніть у закладу, перш ніж іти.",
  "Opening hours": "Години роботи",
  "Today": "Сьогодні",
  "No fixed hours filed. This room opens when something is on; the listings above carry the times.": "Постійних годин немає. Зал відчиняється, коли щось відбувається; час указано в подіях вище.",
  "Not listed. Half the places list their hours, and we would rather leave a gap than guess.": "Не вказано. Половина місць не публікує години, і ми краще залишимо прогалину, ніж будемо вгадувати.",
  "Your lists": "Ваші списки",
  "Create your first list": "Створіть перший список",
  "New list": "Новий список",
  "Create and add": "Створити й додати",
  "Kalamaja on Saturday": "Kalamaja в суботу",
  "Walk": "Пішки",
  "Area": "Район",
  "Set a start point to see the walk": "Вкажіть точку старту, щоб побачити час пішки",
  "Venue logo": "Логотип місця",
  "Venue photo": "Фото місця",
  "Save": "Зберегти",
  "List": "Список",
  "Map preview unavailable · Open map": "Попередній перегляд мапи недоступний · Відкрити мапу",
  "English": "англійська",
  "Estonian": "естонська",
  "Russian": "російська",
  "Ukrainian": "українська",
  "Finnish": "фінська",
  "Swedish": "шведська",
  "German": "німецька",
  "French": "французька",
  "Spanish": "іспанська",
  "Italian": "італійська",
  "Latvian": "латиська",
  "Lithuanian": "литовська",
  "Polish": "польська",
  "Japanese": "японська",
  "Chinese": "китайська",
  "Korean": "корейська",
  "An excerpt.": "Уривок.",
  "Source description": "Опис джерела",
  "Original description": "Оригінальний опис",
  "On now": "Триває зараз",
  "Ongoing": "Триває",
  "Nothing else listed here yet": "Тут поки більше нічого немає",
  "Cancelled": "Скасовано",
  "Postponed": "Перенесено",
  "The source says this will not go ahead.": "За даними джерела, це не відбудеться.",
  "The source says this is moving to a new date. Check there before you go.": "За даними джерела, дату переносять. Перевірте там, перш ніж іти.",
  "Entry": "Вхід",
  "Sold out": "Розпродано",
  "Few tickets left": "Залишилося мало квитків",
  "Check for returns": "Перевірте повернення",
  "Tickets": "Квитки",
  "Website": "Сайт",
  "Instagram": "Instagram",
  "Facebook": "Facebook",
  "Shut": "Зачинено",
  "Place": "Місце",
  "Next": "Далі",
  "Free": "Безкоштовно",
  "Walk in": "Без запису",
  "Following": "Ви підписані",
  "Follow": "Підписатися",
  "Their own channels above carry what we have not read.": "Те, чого ми не прочитали, є в їхніх власних каналах вище.",
  "Follow it and its listings are marked for you when they arrive.": "Підпишіться, і його події позначатимуться для вас, щойно з'являться.",
  "This listing could not load.": "Не вдалося завантажити цю подію.",
  "Check your connection and try again.": "Перевірте з'єднання і спробуйте ще раз.",
  "We have no listing at that address.": "За цією адресою в нас немає події.",
  "The link may be mistyped, or it may be older than a change here.": "Посилання могло бути введене з помилкою або застаріти після змін.",
  "That event is no longer in the programme.": "Цієї події вже немає в програмі.",
  "Add to a list": "Додати до списку",
  "Thanks. We will check the source": "Дякуємо. Ми перевіримо джерело",
  "Could not send. Try again later": "Не вдалося надіслати. Спробуйте пізніше",
  "Undo": "Скасувати",
  "Removed from saved": "Вилучено зі збереженого",
  "Link copied": "Посилання скопійовано",
  "Could not copy the link": "Не вдалося скопіювати посилання",
  "Copied": "Скопійовано",
  "Failed": "Не вдалося",
  "Cities": "Міста",
  "Nearby": "Поруч",
  "Soon": "Незабаром",
  "Clear all": "Очистити все",
  "Gigs": "Концерти",
  "Club nights": "Клубні вечори",
  "Film": "Кіно",
  "Theatre and dance": "Театр і танець",
  "Talks": "Лекції та зустрічі",
  "Workshops": "Майстер-класи",
  "Festivals": "Фестивалі",
  "Helsinki, Finland": "Гельсінкі, Фінляндія",
  "This weekend": "Цими вихідними",
  "Any day": "Будь-який день",
  "Anything": "Будь-що",
  "Only sources I follow": "Лише джерела, на які я підписаний",
  "Show the next few hours": "Показати найближчі години",
  "What's the mood?": "Який настрій?",
  "No selection means all": "Без вибору підходить усе",
  "Up to €20": "До 20 €",
  "Unknown prices included": "Без ціни теж показуємо",
  "Narrow it down": "Уточнити",
  "Art & film": "Мистецтво і кіно",
  "Galleries, cinema, stage, comedy": "Галереї, кіно, сцена, комедія",
  "Stage": "Сцена",
  "Live music": "Жива музика",
  "Gigs, jazz, concerts": "Концерти, джаз, живі виступи",
  "Indie & rock": "Інді та рок",
  "Techno, house, DJs": "Техно, хаус, діджеї",
  "Records & books": "Платівки та книжки",
  "Vinyl, books, thrift, markets": "Вініл, книжки, секонд-хенд, ярмарки",
  "Markets": "Ярмарки",
  "Workshops & talks": "Майстер-класи та лекції",
  "Make, learn, meet people": "Створювати, вчитися, знайомитися",
  "Taprooms and brewery bars": "Пивні та бари броварень",
  "any price": "будь-яка ціна",
  "free": "безкоштовно",
  "Walking from you needs location. Allow it for this site in your browser settings.": "Щоб рахувати шлях від вас, потрібна геолокація. Дозвольте її для цього сайту в налаштуваннях браузера.",
  "Nothing is a short walk from you. Turn Near me off for the whole city.": "Поруч із вами нічого немає. Вимкніть «Поруч зі мною», щоб бачити все місто.",
  "Nearest to you first": "Спершу найближчі до вас",
  "Right by you": "Зовсім поруч із вами",
  "Kind": "Вид",
  "Moods": "Настрої",
  "Kind of place": "Тип місця",
  "nearest to you first": "спершу найближчі до вас",
  "Nearest the centre first": "Спершу найближчі до центру",
  "Change": "Змінити",
  "Ticket price limit": "Ліміт ціни квитка",
  "Day": "День",
  "Still going": "Ще триває",
  "The next few hours": "Найближчі години",
  "Quiet tonight": "Сьогодні ввечері тихо",
  "Near me": "Поруч зі мною",
  "Your saves still work. Try again in a moment.": "Ваше збережене й далі працює. Спробуйте за хвилину.",
  "The sources are read every six hours. The Guide has picked places.": "Джерела читаються кожні шість годин. У гіді — вибрані місця.",
  "Worth the walk": "Варто прогулянки",
  "Picked places": "Вибрані місця",
  "The Guide": "Гід",
  "What's on": "Що відбувається",
  "We can't reach the listings right now.": "Зараз не вдається отримати події.",
  "Hours not listed": "Години не вказано",
  "Open for events": "Відчинено під час подій",
  "Details from the venue; its own site says it opens for its events.": "Відомості від самого місця; його сайт каже, що воно відчинене під час подій.",
  "Address and links from OpenStreetMap; its own site says it opens for its events.": "Адреса й посилання з OpenStreetMap; сайт місця каже, що воно відчинене під час подій.",
  "Unknown": "Невідомо",
  "WanderAlt is already on your Home Screen.": "WanderAlt уже на вашому головному екрані.",
  "This in-app browser cannot add WanderAlt to the Home Screen. Open": "Цей вбудований браузер не може додати WanderAlt на головний екран. Відкрийте",
  "The app starts empty. Sign in first and your saves come with you.": "Застосунок запускається порожнім. Спершу увійдіть, і збережене буде з вами.",
  "Sign in first": "Спершу увійдіть",
  "This browser cannot install WanderAlt.": "Цей браузер не може встановити WanderAlt.",
  "Not now": "Не зараз",
  "Install": "Установити",
  "I have added it": "Я додав",
  "One tap, full screen, and alerts when a plan changes.": "Один дотик, повний екран і сповіщення про зміни планів.",
  "One tap from your Home screen, and alerts when a plan changes.": "Один дотик із головного екрана і сповіщення про зміни планів.",
  "Opens in its own window, one tap away.": "Відкривається у власному вікні, в один дотик.",
  "Add to Home Screen": "Додати на головний екран",
  "Install the app": "Установити застосунок",
  "Add to Home screen": "Додати на головний екран",
  "Open the menu": "Відкрийте меню",
  "Tap the ≡ button in the browser.": "Натисніть кнопку ≡ у браузері.",
  "Add page to": "Додати сторінку на",
  "Choose Add page to, then Home screen. If you see Install, use that.": "Оберіть «Додати сторінку на», потім «Головний екран». Якщо бачите «Установити», оберіть його.",
  "Confirm": "Підтвердити",
  "Tap Add.": "Натисніть «Додати».",
  "Tap the ⋮ button in the browser.": "Натисніть кнопку ⋮ у браузері.",
  "Install app": "Установити застосунок",
  "Choose Install app, or Add to Home screen.": "Оберіть «Установити застосунок» або «Додати на головний екран».",
  "Tap Install or Add.": "Натисніть «Установити» або «Додати».",
  "Tap Share, the square with an arrow, at the top of the screen.": "Натисніть «Поділитися» — квадрат зі стрілкою — вгорі екрана.",
  "Tap Share, the square with an arrow, in the toolbar or address bar.": "Натисніть «Поділитися» — квадрат зі стрілкою — на панелі інструментів або в адресному рядку.",
  "Tap the menu beside the address bar (≡ or ⋯), then Share.": "Натисніть меню біля адресного рядка (≡ або ⋯), потім «Поділитися».",
  "Scroll the list. Not there? Tap Edit Actions at the bottom.": "Прокрутіть список. Немає? Натисніть «Редагувати дії» внизу.",
  "Open as Web App": "Відкрити як вебзастосунок",
  "It is on by default. Leave it on, then tap Add.": "Його ввімкнено за замовчуванням. Залиште ввімкненим і натисніть «Додати».",
  "Already installed": "Уже встановлено",
  "Notification": "Сповіщення",
  "Alerts when plans change": "Сповіщення про зміни планів",
  "Cancellations, and tonight at places you follow": "Скасування і сьогоднішній вечір у місцях, на які ви підписані",
  "Set up": "Налаштувати",
  "Make it an app": "Зробити застосунком",
  "Full screen, alerts, one tap": "Повний екран, сповіщення, один дотик",
  "One tap, and alerts": "Один дотик і сповіщення",
  "Its own window, one tap": "Власне вікно, один дотик",
  "Show me": "Показати",
  "Name ideas": "Ідеї назв",
  "Saturday night": "Суботній вечір",
  "Date night": "Вечір для двох",
  "Rainy day": "Дощовий день",
  "Out of town guests": "Гості з іншого міста",
  "Show everything": "Показати все",
  "Pills are events with their start time. A round pin is a place; a vermilion ring means it is open now.": "Пігулки — це події з часом початку. Кругла мітка — місце; кіноварне кільце означає, що воно відчинене зараз.",
  "Nothing in view": "У кадрі нічого немає",
  "Location is off in this browser, so the list is ordered by time": "Геолокацію в цьому браузері вимкнено, тому список упорядковано за часом",
  "Dance": "Танець",
  "Any mood": "Будь-який настрій",
  "Any mood · any price": "Будь-який настрій · будь-яка ціна",
  "On this week": "Цього тижня",
  "Use my location": "Використати геолокацію",
  "What to look for": "Що шукати",
  "Records": "Платівки",
  "Books": "Книжки",
  "Galleries": "Галереї",
  "Thrift": "Секонд-хенд",
  "Cinema": "Кіно",
  "Clubs and bars": "Клуби та бари",
  "Theatres": "Театри",
  "Community": "Спільнота",
  "No places are filed yet.": "Місць поки немає.",
  "Try again in a moment.": "Спробуйте за хвилину.",
  "None with filed hours are open now.": "Зараз немає відчинених місць із вказаними годинами.",
  "Other kinds of place are.": "Інші види місць відчинені.",
  "All places": "Усі місця",
  "We can't reach the places right now.": "Зараз не вдається отримати місця.",
  "Tonight's listings": "Події сьогоднішнього вечора",
  "From": "Від",
  "Anywhere": "Будь-де",
  "Order": "Порядок",
  "Soonest": "Раніше за часом",
  "Nearest": "Ближче до вас",
  "Starts": "Початок",
  "Walking distance": "Відстань пішки",
  "Free entry": "Вхід вільний",
  "Hide what I've opened": "Сховати відкрите мною",
  "Followed places only": "Лише ваші підписки",
  "New since last visit": "Нові після останнього візиту",
  "Clear all filters": "Скинути всі фільтри",
  "Measure from": "Рахувати відстань від",
  "Search the words": "Шукати слова",
  "Add to calendar": "Додати в календар",
  "Evenings": "Вечори",
  "Maximum walking distance": "Максимальна відстань пішки",
  "My location": "Моя геолокація",
  "Any time": "Будь-коли",
  "From now": "Відтепер",
  "After 21:00": "Після 21:00",
  "After 23:00": "Після 23:00",
  "In English": "Англійською",
  "Pick dates": "Вибрати дати",
  "Follow venues first": "Спершу підпишіться на місця",
  "Anywhere in the city": "Будь-де в місті",
  "Clear for device location": "Очистьте поле для геолокації",
  "Choose a starting point": "Виберіть початкову точку",
  "Clear search": "Очистити пошук",
  "Any kind": "Будь-який вид",
  "Include paid": "Разом із платними",
  "Any price": "Будь-яка ціна",
  "Any language": "Будь-яка мова",
  "Any start time": "Будь-який час початку",
  "Any distance": "Будь-яка відстань",
  "Every source": "Усі джерела",
  "Not only new": "Не лише нові",
  "No listings match this search.": "Жодна подія не відповідає цьому пошуку.",
  "Searches English and original titles, venues and areas, with or without Estonian letters.": "Шукає за англійськими й оригінальними назвами, місцями та районами, з естонськими літерами чи без них.",
  "Nothing matches all of that.": "Ніщо не відповідає всьому цьому одразу.",
  "Try a different day or start a new search.": "Спробуйте інший день або почніть новий пошук.",
  "Start over": "Почати знову",
  "Following this search": "Ви стежите за цим пошуком",
  "Follow this search": "Стежити за цим пошуком",
  "Nothing is listed at these places in the coming days.": "У цих місцях на найближчі дні нічого не заявлено.",
  "Stopped following this search": "Ви більше не стежите за цим пошуком",
  "Include what I've opened": "Разом із тим, що я відкривав",
  "This is what a notification looks like. Nothing to do.": "Так виглядає сповіщення. Нічого робити не потрібно.",
  "New": "Нове",
  "Picked": "Вибране",
  "No date filed": "Дату не вказано",
  "Running": "Триває",
  "Started earlier, still on": "Почалося раніше, ще триває",
  "Club night": "Клубний вечір",
  "Theatre": "Театр",
  "Workshop": "Майстер-клас",
  "Exhibition": "Виставка",
  "Talk": "Лекція",
  "Festival": "Фестиваль",
  "Market": "Ярмарок",
  "Record shop": "Магазин платівок",
  "Bookshop": "Книгарня",
  "Gallery": "Галерея",
  "Thrift shop": "Секонд-хенд",
  "Arts centre": "Центр мистецтв",
  "Community centre": "Громадський центр",
  "Museum": "Музей",
  "Craft beer": "Крафтове пиво",
  "Club": "Клуб",
  "Experimental": "Експериментальне",
  "Techno": "Техно",
  "House": "Хаус",
  "Electronic": "Електроніка",
  "Ambient": "Ембієнт",
  "Noise": "Нойз",
  "Punk": "Панк",
  "Indie": "Інді",
  "Jazz": "Джаз",
  "Folk": "Фолк",
  "Hip-hop": "Хіп-хоп",
  "Metal": "Метал",
  "Rock": "Рок",
  "Classical": "Класика",
  "Queer": "Квір",
  "Drag": "Драг",
  "Poetry": "Поезія",
  "Zines": "Зіни",
  "Vinyl": "Вініл",
  "Arthouse": "Артхаус",
  "Documentary": "Документальне кіно",
  "Contemporary": "Сучасне",
  "Stand-up": "Стендап",
  "Comedy": "Комедія",
  "Improv": "Імпровізація",
  "Satire": "Сатира",
  "Political": "Політика",
  "Design": "Дизайн",
  "Fashion": "Мода",
  "Sauna": "Сауна",
  "Climate": "Клімат",
  "Photography": "Фотографія",
  "Print": "Друк",
  "Illustration": "Ілюстрація",
  "Open mic": "Відкритий мікрофон",
  "Karaoke": "Караоке",
  "Life drawing": "Малювання з натури",
  "Easy alone": "Легко самому",
  "Independent stage": "Незалежна сцена",
  "Sunday": "Неділя",
  "Monday": "Понеділок",
  "Tuesday": "Вівторок",
  "Wednesday": "Середа",
  "Thursday": "Четвер",
  "Friday": "Пʼятниця",
  "Saturday": "Субота",
  "Listed as closed": "Позначено як закрите",
  "Status unverified": "Статус не підтверджено",
  "Open, 24 hours": "Відчинено цілодобово",
  "Shut today": "Сьогодні зачинено",
  "Tmrw": "Завтра",
  "Time not listed": "Час не вказано",
  "Open": "Відчинено",
  "You, signed in": "Ви, вхід виконано",
  "Põhja-Tallinna": "Північного Таллінна",
  "Wrong time or date": "Неправильний час або дата",
  "Wrong venue": "Неправильне місце",
  "Cancelled or moved": "Скасовано або перенесено",
  "Listed twice": "Вказано двічі",
  "Something else": "Щось інше",
  "More routes": "Ще маршрути",
  "No route right now": "Зараз маршруту немає",
  "Nothing fits together right now.": "Зараз нічого не складається докупи.",
  "A walk through Tallinn": "Прогулянка Таллінном",
  "View walk": "Переглянути прогулянку",
  "A gallery": "Галерея",
  "An arts centre": "Центр мистецтв",
  "A film": "Фільм",
  "A museum": "Музей",
  "A thrift shop": "Секонд-хенд",
  "A place": "Місце",
  "Show everything saved": "Показати все збережене",
  "A saved listing": "Збережена подія",
  "Remove": "Видалити",
  "Name it": "Назвіть",
  "Create": "Створити",
  "Lists": "Списки",
  "Only what is in this list.": "Лише те, що в цьому списку.",
  "Nothing saved yet.": "Поки нічого не збережено.",
  "Save from any listing. It waits here, even offline.": "Зберігайте з будь-якої події. Вона чекатиме тут, навіть офлайн.",
  "Saved listings awaiting details": "Збережені події, що чекають на подробиці",
  "Over since you saved it": "Завершилося після збереження",
  "A listing": "Подія",
  "No source named.": "Джерело не вказано.",
  "This page needs a source to show.": "Цій сторінці потрібне джерело.",
  "A source we read": "Джерело, яке ми читаємо",
  "Venue": "Місце",
  "Source excerpt unavailable": "Уривок із джерела недоступний",
  "Auto": "Авто",
  "Light": "Світла",
  "Dark": "Темна",
  "Switch to light mode": "Перемкнути на світлу тему",
  "Switch to dark mode": "Перемкнути на темну тему",
  "Show password": "Показати пароль",
  "Hide password": "Сховати пароль",
  "No description filed": "Опис не вказано",
  "Alerts need the app on your Home Screen.": "Для сповіщень застосунок має бути на головному екрані.",
  "Blocked": "Заблоковано",
  "Notifications on this device": "Сповіщення на цьому пристрої",
  "Saved plan changes": "Зміни збережених планів",
  "Tonight from followed places": "Сьогодні у ваших підписок",
  "Send a test notification": "Надіслати тестове сповіщення",
  "Clear inbox": "Очистити вхідні",
  "Starting point": "Початкова точка",
  "Google": "Google",
  "Your taste": "Ваш смак",
  "Start from": "Звідки йдемо",
  "Appearance": "Оформлення",
  "Unfollow": "Відписатися",
  "Follow a venue from its page.": "Підпишіться на місце на його сторінці.",
  "Forget what I've opened": "Забути відкрите",
  "Nothing opened yet.": "Поки нічого не відкрито.",
  "Sign out": "Вийти",
  "Delete account": "Видалити акаунт",
  "The full note": "Повна нотатка",
  "Calendar feed": "Календарна стрічка",
  "Forget everything on this device": "Забути все на цьому пристрої",
  "Add this to your calendar": "Додати до календаря",
  "Could not save. Try again later": "Не вдалося зберегти. Спробуйте пізніше",
  "Open Settings, then Notifications, then WanderAlt, and allow notifications.": "Відкрийте «Параметри», потім «Сповіщення», потім WanderAlt і дозвольте сповіщення.",
  "Notifications are blocked for this site in your browser settings.": "Сповіщення для цього сайту заблоковано в налаштуваннях браузера.",
  "Just now": "Щойно",
  "Checked just now": "Перевірено щойно",
  "Inbox": "Вхідні",
  "Kept for 30 days": "Зберігається 30 днів",
  "Nothing yet.": "Поки нічого.",
  "Notifications": "Сповіщення",
  "Walks start here": "Прогулянки починаються тут",
  "A venue": "Місце",
  "A saved search": "Збережений пошук",
  "Account": "Обліковий запис",
  "Data and privacy": "Дані та приватність",
  "Notifications were not allowed": "Сповіщення не дозволено",
  "Could not clear. Try again later": "Не вдалося очистити. Спробуйте пізніше",
  "Forgot what you opened": "Забуто, що ви відкривали",
  "Sent": "Надіслано",
  "Could not send": "Не вдалося надіслати",
  "Delete your account?": "Видалити обліковий запис?",
  "Could not delete the account. Nothing was changed": "Не вдалося видалити обліковий запис. Нічого не змінено",
  "Forget everything on this device?": "Забути все на цьому пристрої?",
  "Forget everything": "Забути все",
  "Language": "Мова",
  "Price not listed": "Ціну не вказано",
  "Show the map": "Показати карту",
  "Primary": "Основна",
  "WanderAlt, Tallinn tonight": "WanderAlt, Таллінн сьогодні ввечері",
  "Toggle attribution": "Показати або сховати джерела",
  "Art": "Мистецтво",
  "Gig": "Концерт",
  "Bar": "Бар",
  "hours not listed": "години не вказано",
  "open": "відчинено",
  "Listed here next": "Далі тут",
  "OpenStreetMap": "OpenStreetMap",
  "the venue's own site": "власного сайту закладу",
  "OpenStreetMap or the venue's own site": "OpenStreetMap або власного сайту закладу",
  "MON": "ПН",
  "TUE": "ВТ",
  "WED": "СР",
  "THU": "ЧТ",
  "FRI": "ПТ",
  "SAT": "СБ",
  "SUN": "НД",
  "soonest first": "спершу найближчі за часом",
  "nearest first": "спершу найближчі",
  "No places match this search.": "Жодне місце не відповідає цьому пошуку.",
  "Places without filed hours aren't included.": "Місця без вказаних годин не включено.",
  "This walk is no longer available": "Ця прогулянка більше недоступна",
  "Choose a walk for today.": "Виберіть прогулянку на сьогодні.",
  "Its date or stops have changed. Now has walks for the next few hours.": "Дата або зупинки змінилися. У розділі «Зараз» є прогулянки на найближчі години.",
  "Place types": "Типи місць",
  "With known hours": "З відомими годинами роботи",
  "All place types in the Guide": "Усі типи місць у путівнику",
  "Show all matching places": "Показати всі відповідні місця",
  "picked first": "спершу вибрані місця",
  "the city centre": "центр міста",
  "Search places or listings": "Шукати місця або події",
  "Try another area, a longer walk or another kind of place.": "Спробуйте інший район, довшу прогулянку або інший тип місця.",
  "including closed places": "включно із зачиненими місцями",
  "Couldn't refresh. Showing last loaded listings.": "Не вдалося оновити. Показано раніше завантажені події.",
  "We can't load listings right now.": "Зараз не вдається завантажити події.",
  "Trying again…": "Пробуємо ще раз…",
  "DIY gigs, club nights, arthouse film, contemporary art and dance, talks and markets, and the shops and rooms that host them. No hosts, no bookings, no commission. If a listing is wrong, the venue's own page is wrong, and we say where we read it.": "DIY-концерти, клубні вечірки, авторське кіно, сучасне мистецтво й танець, лекції та маркети, а також крамниці й простори, де все це відбувається. Без посередників, бронювань і комісій. Якщо в події помилка, то вона на сторінці самого місця, і ми вказуємо, де це прочитали.",
  "Saves, interests and what you open stay in your browser.": "Збережене, інтереси й те, що ви відкриваєте, лишаються у вашому браузері.",
  "Signed in, your saves, lists, follows, going marks and alert settings also live in your account, with your inbox, until you delete it.": "Якщо ви ввійшли, збережене, списки, підписки, позначки «піду» та налаштування сповіщень зберігаються й у вашому обліковому записі разом із вхідними, доки ви його не видалите.",
  "Delete your account": "Видалити обліковий запис",
  "Google sign-in gives us your email address and nothing else.": "Вхід через Google передає нам лише вашу адресу електронної пошти.",
  "Alerts stay in the app, and a push goes only to a device you allow.": "Сповіщення лишаються в застосунку, а push надходить лише на пристрій, який ви дозволили.",
  "We send no email announcements.": "Ми не надсилаємо листів з оголошеннями.",
  "No cookies to consent to, no analytics, no third-party scripts.": "Жодних cookie-банерів, аналітики чи сторонніх скриптів.",
  "What we read about venues, including their public Facebook and Instagram business pages, and how a venue has it removed:": "Що ми читаємо про місця, зокрема на їхніх публічних бізнес-сторінках у Facebook та Instagram, і як місце може видалити ці дані:",
  "Facts about venues (opening hours, website, a one-line description, a logo) come from the venue's own site, OpenStreetMap, Wikidata, and the public Facebook Page and Instagram business account of the venue, read through Meta's official API.": "Відомості про місця (години роботи, сайт, опис в один рядок, логотип) беруться із сайту самого місця, з OpenStreetMap і Wikidata, а також із публічної сторінки місця у Facebook та його бізнес-акаунта в Instagram через офіційний API Meta.",
  "We read business pages only, never a person's profile, and keep no contact details.": "Ми читаємо лише сторінки організацій, ніколи не профілі людей, і не зберігаємо контактних даних.",
  "A venue that wants a fact corrected or its details removed writes to us at": "Місце, яке хоче виправити відомості про себе або видалити їх, пише нам на",
  "We do it within 30 days and stop reading its pages.": "Ми робимо це протягом 30 днів і перестаємо читати його сторінки.",
  "Signed-in visitors can delete their account and everything in it:": "Користувачі, які ввійшли, можуть видалити свій обліковий запис і все, що в ньому:",
  "Listings belong to the venues and sources they came from, and we link to each one.": "Події належать місцям і джерелам, звідки їх узято, і ми посилаємося на кожне.",
  "We print what the source said and when we read it.": "Ми показуємо, що сказало джерело і коли ми це прочитали.",
  "We cannot promise a door will be open.": "Ми не можемо обіцяти, що двері будуть відчинені.",
  "Another": "Інший",
  "Any": "Будь-яка",
  "Open in Maps": "Відкрити в Картах",
  "Walking times follow the streets at an easy pace.": "Час пішки пораховано вулицями, спокійним кроком.",
  "Place times are suggested.": "Час відвідування місць запропоновано для плану.",
  "Place costs are not included.": "Витрати в закладах не враховано.",
  "Some opening hours are not listed. Check before you go.": "Години роботи деяких місць не вказано. Перевірте перед виходом.",
  "The event end time is not listed. Later stops are flexible.": "Час завершення події не вказано. Наступні зупинки можна змістити.",
  "Some stops have no map location. Open their pages for address details.": "Деякі зупинки не позначено на мапі. Адреси дивіться на їхніх сторінках.",
  "Tickets and opening hours can change. Check each stop before you go.": "Наявність квитків і години роботи можуть змінитися. Перевірте кожну зупинку перед виходом.",
  "Was": "Минуло",
  "closed": "зачинено",
  "where you are": "вас",
  "your chosen place": "вибраного місця",
  "Price not listed.": "Ціну не вказано.",
  "Free entry.": "Вхід вільний.",
  "free entry": "вхід вільний",
  "A bar": "Бар",
  "A club": "Клуб",
  "A gig": "Концерт",
  "A club night": "Клубна ніч",
  "A stage": "Вистава",
  "A talk": "Лекція",
  "A workshop": "Майстер-клас",
  "An opening": "Відкриття",
  "A festival": "Фестиваль",
  "A show": "Подія",
  "A late drink": "Пізній келих",
  "A drink": "Келих",
  "Another late drink": "Ще один пізній келих",
  "Another drink": "Ще келих",
  "Another club": "Ще один клуб",
  "Another bar": "Ще один бар",
  "Another film": "Ще один фільм",
  "Another gallery": "Ще одна галерея",
  "Another thrift shop": "Ще один секонд-хенд",
  "Source:": "Джерело:",
  "© OpenStreetMap contributors": "© Учасники OpenStreetMap",
  "City or place": "Місто або місце",
  "Choose a nearby venue": "Виберіть місце поблизу",
  "Using your location": "Використовується ваша геолокація",
  "Location is blocked. Allow it in browser settings, or choose a place.": "Геолокацію заблоковано. Дозвольте її в налаштуваннях браузера або виберіть місце.",
  "Could not get your location. Try again or choose a place.": "Не вдалося визначити місцезнаходження. Спробуйте ще раз або виберіть місце.",
  "Nothing is a short walk from here. Choose another starting point or Whole city.": "Поруч нічого немає. Виберіть іншу точку відліку або Все місто.",
  "Whole city": "Все місто",
  "Choose a place": "Виберіть місце",
  "Right by here": "Зовсім поруч",
  "Nearest to here first": "Спершу найближчі звідси",
  "A walk for now": "Прогулянка зараз",
  "Two or three stops on foot": "Дві або три зупинки пішки",
  "Show results": "Показати результати",
  "Date": "Дата",
  "Date range": "Діапазон дат",
  "Through": "До",
  "Apply": "Застосувати",
  "No listings match these choices.": "Немає подій за вибраними умовами.",
  "Source": "Джерело",
  "Venue image": "Фото місця",
  "Hours shown for now": "Години роботи зараз",
  "Map of Tallinn": "Мапа Таллінна",
  "No places match these choices.": "Немає місць за вибраними умовами.",
  "Zoom out or move the map.": "Зменште масштаб або посуньте мапу.",
  "Events layer off": "Шар подій вимкнено",
  "Location needed; showing soonest": "Потрібна геолокація; спершу ранні",
  "At 16:00 when listed": "О 16:00, якщо заплановано",
  "After": "Після",
  "Your saves carry over": "Збережене залишиться з вами",
  "No password needed": "Пароль не потрібен",
  "Signed in": "Ви ввійшли",
  "Your saves sync between devices.": "Збережене синхронізується між пристроями.",
  "Saved in this browser": "Збережено в цьому браузері",
  "Stays in this browser.": "Зберігається в цьому браузері.",
  "No signal": "Немає зв’язку",
  "Showing last loaded listings": "Останні завантажені події",
  "Saves work offline": "Збережене доступне без мережі",
  "Distances won't update": "Відстані не оновлюються",
  "cached just now": "щойно завантажено",
  "price not listed": "ціну не вказано",
  "it has already happened": "уже відбулося",
  "it is no longer in the programme": "більше немає в програмі",
  "it is no longer listed": "більше немає в списку",
  "Details are loading": "Дані завантажуються",
  "Details could not load": "Не вдалося завантажити дані",
  "These saves are kept": "Збережене залишається на місці",
  "This is our reading of the listing; the organiser has not confirmed it.": "Це наше прочитання події; організатор його не підтвердив.",
  "a quiz": "вікторина",
  "a game night": "вечір настільних ігор",
  "a craft club": "гурток рукоділля",
  "an open stage": "відкрита сцена",
  "a drawing night": "вечір малювання",
  "a language night": "мовний вечір",
  "a night for meeting people": "вечір знайомств",
  "a club night": "клубний вечір",
  "a night": "вечір",
  "Try a different time or starting point, or browse the picked places in the Guide.": "Спробуйте інший час або початкову точку чи перегляньте вибрані місця в гіді.",
  "Your saves, lists, follows, alerts and inbox are removed, and this device forgets them too. This cannot be undone.": "Ваші збереження, списки, підписки, сповіщення та вхідні буде видалено, зокрема з цього пристрою. Скасувати це неможливо.",
  "Saves, lists, follows and history are cleared from this browser and you are signed out. An account keeps its saves; sign in to bring them back.": "Збереження, списки, підписки та історію буде видалено з цього браузера, і ви вийдете з облікового запису. Збережене в обліковому записі залишиться; увійдіть, щоб повернути його.",
  "Closed or moved?": "Зачинено чи переїхало?",
  "Flagged by readers": "Повідомлення читачів",
  "Facts that may have changed": "Можливі зміни",
  "Different places": "Різні місця",
  "Open the event": "Відкрити подію",
  "Open the place": "Відкрити місце",
  "Withhold the place": "Приховати місце",
  "Use the new value": "Використати нове значення",
  "Keep what we hold": "Залишити поточні дані",
  "Fixed": "Виправлено",
  "Dismiss": "Відхилити",
  "Publish": "Опублікувати",
  "Reject": "Відхилити",
  "Possible duplicate places": "Можливі дублікати місць",
  "Review queue": "Черга перевірки",
  "Events the pipeline held back. Publish what belongs, reject what does not; the pipeline never changes a decision made here.": "Події, відкладені збирачем. Публікуйте відповідні, відхиляйте решту; збирач не змінює ухвалених тут рішень.",
  "Supabase secret key": "Секретний ключ Supabase",
  "Kept in this tab only (sessionStorage) and sent only to Supabase.": "Зберігається лише в цій вкладці (sessionStorage) і надсилається лише до Supabase.",
  "Open the queue": "Відкрити чергу",
  "Around here": "Поблизу",
  "Within 10 minutes’ walk": "До 10 хв пішки",
  "Continue with Google": "Продовжити з Google",
  "or": "або",
  "We hold:": "Поточні дані:",
  "Nothing filed": "Немає даних",
  "Email alerts": "Сповіщення поштою",
  "This link is not valid.": "Це посилання недійсне.",
  "Stop email and notifications?": "Вимкнути листи та сповіщення?",
  "Stop alerts": "Вимкнути сповіщення",
  "That did not work. Write to hello@wanderalt.app and we will stop it by hand.": "Не вдалося. Напишіть на hello@wanderalt.app, і ми вимкнемо сповіщення вручну.",
  "Done. No more email or notifications from WanderAlt. You can switch alerts on again from You.": "Готово. Листи та сповіщення WanderAlt вимкнено. Увімкнути їх знову можна в профілі.",
  "Search events or places": "Пошук подій або місць",
  "Close search": "Закрити пошук",
  "All events": "Усі події",
  "Search results": "Результати пошуку",
  "All dates": "Усі дати",
  "Refine": "Уточнити",
  "Try a search": "Спробуйте пошук",
  "Jazz tomorrow": "Джаз завтра",
  "Record shops": "Магазини платівок",
  "Free today": "Безкоштовно сьогодні",
  "View all results": "Усі результати",
  "No matches. Try another name or browse all events and places.": "Збігів немає. Спробуйте іншу назву або перегляньте всі події та місця.",
  "Loading listings": "Завантаження подій",
  "Selected filters": "Вибрані фільтри",
  "Map these results": "Ці результати на мапі",
  "Back to results": "Назад до результатів",
  "With a listed language": "Із вказаною мовою",
  "All places and All events have the complete listings.": "Повні списки є в розділах «Усі місця» та «Усі події».",
  "Price per ticket": "Ціна квитка",
  "Maximum price per ticket": "Максимальна ціна квитка",
  "More options": "Більше параметрів",
  "Sources go quiet between programmes. All events has the full listing.": "Між подіями джерела затихають. Повний список є в розділі «Усі події».",
  "Keywords": "Ключові слова",
  "Filters from your search": "Фільтри з вашого запиту",
  "Keep this search": "Зберегти цей пошук",
  "Near you": "Поруч із вами",
  "More filters": "Більше фільтрів",
  "Another walk": "Інша прогулянка",
  "You can still walk in": "Ще можна зайти",
  "Already under way": "Уже триває",
  "Late entry may not be possible": "Запізнілих можуть не пустити",
  "Starting soon": "Незабаром почнеться",
  "In the next two hours": "Протягом двох годин",
  "Later tonight": "Пізніше ввечері",
  "Later today": "Пізніше сьогодні",
  "Until 05:00": "До 05:00",
  "Also today": "Також сьогодні",
  "No set time, or running": "Без часу або триває кілька днів",
  "Cancelled or postponed": "Скасовано або перенесено",
  "Nothing else listed tonight.": "На сьогоднішній вечір більше нічого немає.",
  "Change dates": "Змінити дати",
  "A day or a range": "День або період",
  "Walk and map": "Прогулянка і мапа",
  "Mood": "Настрій",
  "Keep your saves on every device": "Збережене на всіх пристроях",
  "Optional. No password.": "За бажанням. Без пароля.",
  "Saves sync to your account": "Збережене синхронізується з акаунтом",
  "Not set": "Не вибрано",
  "Your location": "Ваше розташування",
  "Recently opened": "Нещодавно відкриті",
  "Up to three. Walks lean toward them; nothing is hidden.": "До трьох. Прогулянки враховують їх, нічого не приховується.",
  "Follow a place or a source from its page to hear when it lists something new.": "Підпишіться на місце чи джерело на його сторінці, щоб дізнаватися про нові події.",
  "Nothing yet. Notes about saved plans arrive here.": "Поки нічого. Сюди надходять нотатки про збережені плани.",
  "Your saves and history stay in this browser. Signed in, they also live in your account until you delete it.": "Збережене та історія лишаються в цьому браузері. Після входу вони зберігаються й в акаунті, доки ви його не видалите.",
  "On this device": "На цьому пристрої",
  "Waiting to sync": "Очікує синхронізації",
  "Synced": "Синхронізовано",
  "Walk your saves": "Прогулянка збереженим",
  "Nothing in this list yet. Add saves to it from their pages.": "У цьому списку поки порожньо. Додавайте збережене зі сторінок подій і місць.",
  "Needs the app": "Потрібен застосунок",
  "On": "Увімк.",
  "Off": "Вимк.",
  "Clear filters": "Скинути фільтри",
  "Only confirmed free listings": "Лише події з підтвердженим безкоштовним входом",
  "Wellness and spiritual": "Велнес і духовні практики",
  "Hobby classes": "Хобі-заняття",
  "Self-help and social": "Саморозвиток і спілкування",
  "Mainstream and commercial": "Мейнстрим і комерція",
  "Children's events": "Дитячі події",
  "At a restaurant": "У ресторані",
  "At a hotel": "У готелі",
  "At a yoga or wellness studio": "У студії йоги чи велнесу",
  "At a puppet theatre or youth centre": "У ляльковому театрі чи молодіжному центрі",
  "At an arena": "На арені",
  "Dates read from a poster": "Дати прочитано з афіші",
  "Trusted source, low fit": "Надійне джерело, слабка відповідність",
  "Borderline fit": "Прикордонна відповідність",
  "Other reasons": "Інші причини",
  "Reject this group": "Відхилити цю групу",
  "Publish this group": "Опублікувати цю групу",
  "Yes, reject": "Так, відхилити",
  "Yes, publish": "Так, опублікувати",
  "The next eight days also come as a feed for readers and newsletters:": "Найближчі вісім днів є й у вигляді стрічки для читалок і розсилок:",
  "Map of the walk": "Мапа прогулянки",
  "A sentence instead of a name": "Фраза замість назви"
 },
 "patterns": [
  [
   "{n} on now",
   "Зараз триває: {n}"
  ],
  [
   "{n} places",
   {
    "one": "{n} місце",
    "few": "{n} місця",
    "many": "{n} місць",
    "other": "{n} місця"
   }
  ],
  [
   "{n} place",
   "{n} місце"
  ],
  [
   "{n} listed",
   {
    "one": "{n} подія",
    "few": "{n} події",
    "many": "{n} подій",
    "other": "{n} події"
   }
  ],
  [
   "{n} listings",
   {
    "one": "{n} подія",
    "few": "{n} події",
    "many": "{n} подій",
    "other": "{n} події"
   }
  ],
  [
   "{n} listing",
   "{n} подія"
  ],
  [
   "{n} min",
   "{n} хв"
  ],
  [
   "{n} min walk",
   "{n} хв пішки"
  ],
  [
   "{n} min walk from you",
   "{n} хв пішки від вас"
  ],
  [
   "{n} h",
   "{n} год"
  ],
  [
   "till {t}",
   "до {t}"
  ],
  [
   "till {d}",
   "до {d}"
  ],
  [
   "Until {t}",
   "До {t}"
  ],
  [
   "Until {d}",
   "До {d}"
  ],
  [
   "Open till {t}",
   "Відчинено до {t}"
  ],
  [
   "open till {t}",
   "відчинено до {t}"
  ],
  [
   "{x} away",
   "за {x}"
  ],
  [
   "Opens {t}",
   "Відчиниться о {t}"
  ],
  [
   "opens {t}",
   "відчиниться о {t}"
  ],
  [
   "Opens {d}",
   "Відчиниться {d}"
  ],
  [
   "closes {t}",
   "зачиниться о {t}"
  ],
  [
   "{d} to {d2}",
   "{d} — {d2}"
  ],
  [
   "from {d}",
   "з {d}"
  ],
  [
   "about {h} h {m} min",
   "близько {h} год {m} хв"
  ],
  [
   "about {h} h",
   "близько {h} год"
  ],
  [
   "about {m} min",
   "близько {m} хв"
  ],
  [
   "tickets from {x}",
   "квитки від {x}"
  ],
  [
   "Up to {x}, about {y}",
   "До {x}, близько {y}"
  ],
  [
   "up to {x}",
   "до {x}"
  ],
  [
   "Show {n} more",
   "Показати ще {n}"
  ],
  [
   "All {n}",
   "Усі {n}"
  ],
  [
   "Show all {n} running",
   "Показати всі {n}, що тривають"
  ],
  [
   "Added to {rawName}",
   "Додано до {rawName}"
  ],
  [
   "Remove {rawTitle} from saved",
   "Прибрати {rawTitle} зі збереженого"
  ],
  [
   "Save: {rawTitle}",
   "Зберегти: {rawTitle}"
  ],
  [
   "Saved: {rawTitle}",
   "Збережено: {rawTitle}"
  ],
  [
   "Also in {rawName}:",
   "Також у районі {rawName}:"
  ],
  [
   "After {rawName}",
   "Після: {rawName}"
  ],
  [
   "{n} of {m}",
   "{n} з {m}"
  ],
  [
   "{rawName} on the map",
   "{rawName} на карті"
  ],
  [
   "{rawName} (opens {y})",
   "{rawName} (відчиниться: {y})"
  ],
  [
   "Logo from {rawName}, their logo",
   "Логотип із {rawName}, їхній власний"
  ],
  [
   "Address and links from OpenStreetMap; hours from {x}.",
   "Адреса й посилання з OpenStreetMap; години роботи: {x}."
  ],
  [
   "Details from the venue; hours from {x}.",
   "Дані від закладу; години роботи: {x}."
  ],
  [
   "Everything from {rawName}",
   "Усе з {rawName}"
  ],
  [
   "Following {rawName}",
   "Ви підписані: {rawName}"
  ],
  [
   "Stopped following {rawName}",
   "Ви більше не підписані: {rawName}"
  ],
  [
   "Nothing is listed in {rawName} for the coming days.",
   "У районі {rawName} на найближчі дні нічого не оголошено."
  ],
  [
   "Nothing is listed in {rawName} yet.",
   "У районі {rawName} поки нічого не оголошено."
  ],
  [
   "Nothing from {rawName} is listed right now.",
   "Від {rawName} зараз нічого не оголошено."
  ],
  [
   "Follow my device, dark from {t}",
   "Як на пристрої, темна з {t}"
  ],
  [
   "Listed via {rawName}",
   "Оголошено через {rawName}"
  ],
  [
   "It was on {d}",
   "Це було {d}"
  ],
  [
   "It came off on {d}",
   "Це завершилося {d}"
  ],
  [
   "Tonight in {x}",
   "Сьогодні ввечері: {x}"
  ],
  [
   "{n} open now",
   "відчинено зараз: {n}"
  ],
  [
   "{n} open",
   "відчинено: {n}"
  ],
  [
   "{n} min ago",
   "{n} хв тому"
  ],
  [
   "{n} hour ago",
   "{n} год тому"
  ],
  [
   "{n} hours ago",
   "{n} год тому"
  ],
  [
   "{n} day ago",
   "{n} дн. тому"
  ],
  [
   "{n} days ago",
   "{n} дн. тому"
  ],
  [
   "Checked {n} min ago",
   {
    "one": "Перевірено {n} хвилину тому",
    "few": "Перевірено {n} хвилини тому",
    "many": "Перевірено {n} хвилин тому",
    "other": "Перевірено {n} хвилини тому"
   }
  ],
  [
   "Checked {n} h ago",
   {
    "one": "Перевірено {n} годину тому",
    "few": "Перевірено {n} години тому",
    "many": "Перевірено {n} годин тому",
    "other": "Перевірено {n} години тому"
   }
  ],
  [
   "Checked {d}",
   "Перевірено {d}"
  ],
  [
   "{n} more listed here",
   "Тут ще {n}"
  ],
  [
   "on {u}",
   "на {u}"
  ],
  [
   "Listed via {rawName}, read {y}.",
   "Оголошено через {rawName}, прочитано {y}."
  ],
  [
   "It was on {d} at {t}.",
   "Це було {d} о {t}."
  ],
  [
   "It was on {d}.",
   "Це було {d}."
  ],
  [
   "{n} min on foot",
   "{n} хв пішки"
  ],
  [
   "{n} free in this view",
   "Безкоштовно в цьому вигляді: {n}"
  ],
  [
   "{n} opened or saved",
   "Відкрито або збережено: {n}"
  ],
  [
   "{n} more after these",
   "Ще {n} після цих"
  ],
  [
   "{n}.{h} km",
   "{n},{h} км"
  ],
  [
   "{n} km",
   "{n} км"
  ],
  [
   "{n} m",
   "{n} м"
  ],
  [
   "{h} h {m} min",
   "{h} год {m} хв"
  ],
  [
   "{h} h",
   "{h} год"
  ],
  [
   "About {a}, {b} on foot.",
   "Близько {a}, пішки {b}."
  ],
  [
   "About {a}.",
   "Близько {a}."
  ],
  [
   "about {a}",
   "близько {a}"
  ],
  [
   "Tickets from {x}.",
   "Квитки від {x}."
  ],
  [
   "{n} price not listed",
   "ціну не вказано: {n}"
  ],
  [
   "{n} stops",
   {
    "one": "{n} зупинка",
    "few": "{n} зупинки",
    "many": "{n} зупинок",
    "other": "{n} зупинки"
   }
  ],
  [
   "{rawName}, Open till {t}",
   "{rawName}, відчинено до {t}"
  ],
  [
   "{rawName}, Opens {t}",
   "{rawName}, відчиниться о {t}"
  ],
  [
   "{rawName}, Shut today",
   "{rawName}, сьогодні зачинено"
  ],
  [
   "{rawName}, Hours not filed",
   "{rawName}, години не вказано"
  ],
  [
   "{rawName}, Open for events",
   "{rawName}, відчинено під час подій"
  ],
  [
   "{rawName}, Open, 24 hours",
   "{rawName}, відчинено цілодобово"
  ],
  [
   "{rawName}, Listed as closed",
   "{rawName}, позначено як зачинене"
  ],
  [
   "{rawName}, Status unverified",
   "{rawName}, статус не підтверджено"
  ],
  [
   "with {w}",
   "зі словом {w}"
  ],
  [
   "Image from {u}",
   "Зображення з {u}"
  ],
  [
   "{n} today",
   "Сьогодні: {n}"
  ],
  [
   "{n} min walk from here",
   "{n} хв пішки звідси"
  ],
  [
   "{n} listings on this map",
   {
    "one": "На цій мапі: {n} подія",
    "few": "На цій мапі: {n} події",
    "many": "На цій мапі: {n} подій",
    "other": "На цій мапі: {n} події"
   }
  ],
  [
   "Language: {rawName}",
   "Мова: {rawName}"
  ],
  [
   "{n} free",
   "{n} безкоштовно"
  ],
  [
   "{n} from followed places",
   "{n} від ваших підписок"
  ],
  [
   "{n} new listings",
   {
    "one": "{n} нова подія",
    "few": "{n} нові події",
    "many": "{n} нових подій",
    "other": "{n} нові події"
   }
  ],
  [
   "Add {rawName} to your calendar",
   "Додати {rawName} до календаря"
  ],
  [
   "Walking from {rawName}",
   "Звідки: {rawName}"
  ],
  [
   "{n} here, zoom in",
   "Тут {n}, наблизити"
  ],
  [
   "{n} min walk from where you are",
   "{n} хв пішки від вас"
  ],
  [
   "cached {x}",
   "завантажено {x}"
  ],
  [
   "The format is {x}, built for people who turn up on their own to mix.",
   "Формат: {x}. Підходить, щоб прийти наодинці й познайомитися з людьми."
  ],
  [
   "Sign-in did not finish: {rawError}",
   "Не вдалося ввійти: {rawError}"
  ],
  [
   "Not saved: {rawError}",
   "Не збережено: {rawError}"
  ],
  [
   "Merge into {rawName}",
   "Об’єднати в {rawName}"
  ],
  [
   "We hold: {rawValue}",
   "Поточні дані: {rawValue}"
  ],
  [
   "It says: {rawValue}",
   "У джерелі: {rawValue}"
  ],
  [
   "{n} waiting",
   "Очікують: {n}"
  ],
  [
   "from its {rawSource}",
   "джерело: {rawSource}"
  ],
  [
   "Supabase refused the key ({rawError}). Check it is the secret key, not the anon key or a Cloudflare token.",
   "Supabase відхилив ключ ({rawError}). Перевірте, що це секретний ключ, а не anon-ключ або токен Cloudflare."
  ],
  [
   "Show {n} listing",
   "Показати {n} подія"
  ],
  [
   "Show {n} listings",
   {
    "one": "Показати {n} подія",
    "few": "Показати {n} події",
    "many": "Показати {n} подій",
    "other": "Показати {n} події"
   }
  ],
  [
   "Show {n} place",
   "Показати {n} місце"
  ],
  [
   "Show {n} places",
   {
    "one": "Показати {n} місце",
    "few": "Показати {n} місця",
    "many": "Показати {n} місць",
    "other": "Показати {n} місця"
   }
  ],
  [
   "since {t}",
   "з {t}"
  ],
  [
   "Show {n} more places",
   {
    "one": "Ще {n} місце",
    "few": "Ще {n} місця",
    "many": "Ще {n} місць",
    "other": "Ще {n} місця"
   }
  ],
  [
   "{n} without a map location",
   "{n} без адреси на мапі"
  ],
  [
   "Dark from {t}",
   "Темна з {t}"
  ],
  [
   "All {n} open",
   "Усі відчинені: {n}"
  ],
  [
   "{x} from {t}",
   "{x} з {t}"
  ],
  [
   "{n} dates",
   {
    "one": "{n} дата",
    "few": "{n} дати",
    "many": "{n} дат",
    "other": "{n} дати"
   }
  ],
  [
   "Publish all {n}",
   "Опублікувати всі: {n}"
  ],
  [
   "Reject all {n}",
   "Відхилити всі: {n}"
  ],
  [
   "Publish {x}?",
   "Опублікувати {x}?"
  ],
  [
   "Reject {x}?",
   "Відхилити {x}?"
  ],
  [
   "{n} sources",
   {
    "one": "{n} джерело",
    "few": "{n} джерела",
    "many": "{n} джерел",
    "other": "{n} джерела"
   }
  ]
 ]
};
