#!/usr/bin/env python3
"""Builds lang/et.js and lang/ru.js from lang/*.tsv (English, Estonian, Russian per line).

  lang/phrases.tsv    exact UI phrases
  lang/patterns.tsv   phrases with {placeholders}; a Russian cell may give plural forms as
                      "one|few|many|other" for the number in {n} (Estonian uses one form)

Run:  python3 tools/build-lang.py
Lines starting with # and blank lines are ignored. A tab is the only separator.
"""
import json, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
def rows(name):
    path = root / 'lang' / name
    if not path.exists(): return []
    out = []
    for n, line in enumerate(path.read_text(encoding='utf8').splitlines(), 1):
        if not line.strip() or line.startswith('#'): continue
        cells = line.split('\t')
        if len(cells) != 3 or not all(c.strip() for c in cells):
            sys.exit(f'{name}:{n}: expected English, Estonian and Russian separated by tabs: {line[:80]!r}')
        out.append([c.strip() for c in cells])
    return out

phrases, patterns = rows('phrases.tsv'), rows('patterns.tsv')
CATS = ['one', 'few', 'many', 'other']
def plural(cell):
    parts = cell.split('|')
    if len(parts) == 1: return cell
    if len(parts) != 4: sys.exit(f'plural forms need four parts one|few|many|other: {cell!r}')
    return dict(zip(CATS, parts))

for code, col, name in (('et', 1, 'Estonian'), ('ru', 2, 'Russian')):
    exact, seen = {}, set()
    for r in phrases:
        if r[0] in seen: sys.exit(f'duplicate phrase: {r[0]!r}')
        seen.add(r[0]); exact[r[0]] = r[col]
    pats = [[r[0], plural(r[col]) if code == 'ru' else r[col].split('|')[0]] for r in patterns]
    body = f"""/* {name}. English phrase → {name}; see i18n.js. Generated by tools/build-lang.py from lang/phrases.tsv
   and lang/patterns.tsv: edit those, not this file. */
window.WA = window.WA || {{}}; window.WA.dict = window.WA.dict || {{}};
window.WA.dict.{code} = {json.dumps({'exact': exact, 'patterns': pats}, ensure_ascii=False, indent=1)};
"""
    (root / 'lang' / f'{code}.js').write_text(body, encoding='utf8')
    print(f'{code}: {len(exact)} phrases, {len(pats)} patterns')
